Foreground true
User clamav
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LocalSocket /run/clamav/clamd.sock
LocalSocketMode 666
FixStaleSocket true
MaxConnectionQueueLength 32
MaxThreads 4
MaxQueue 16
MaxScanSize 100M
MaxFileSize 100M
StreamMaxLength 100M
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 500
OfficialDatabaseOnly true
BytecodeSecurity TrustSigned
LogTime true
LogClean false
