// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ContributionKind,
} from "./types";

export default {
  threadId: __t.uuid(),
  parentContributionId: __t.option(__t.uuid()),
  get kind() {
    return ContributionKind;
  },
  body: __t.string(),
  clientRequestId: __t.uuid(),
};
