// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.uuid().name("run_id"),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  title: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
