// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  OutboxState,
} from "./types";

export default {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  get outcome() {
    return OutboxState;
  },
  lastError: __t.string(),
  retryAfterSeconds: __t.u32(),
};
