// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FileSecurityState,
} from "./types";


export default __t.row({
  jobId: __t.uuid().name("job_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  fileId: __t.uuid().name("file_id"),
  fileRevision: __t.u64().name("file_revision"),
  kind: __t.string(),
  sourceKey: __t.string().name("source_key"),
  sourceObjectVersion: __t.string().name("source_object_version"),
  sourceChecksumSha256: __t.string().name("source_checksum_sha_256"),
  cleanDestinationKey: __t.string().name("clean_destination_key"),
  cleanupPrefix: __t.string().name("cleanup_prefix"),
  maxBytes: __t.u64().name("max_bytes"),
  maxExtractedCharacters: __t.u64().name("max_extracted_characters"),
  allowedTypes: __t.array(__t.string()).name("allowed_types"),
  get state() {
    return FileSecurityState;
  },
  leaseGeneration: __t.u64().name("lease_generation"),
});
