// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptPlatformOperatorTransferReducer from "./accept_platform_operator_transfer_reducer";
import AcquireAgentToolEffectReducer from "./acquire_agent_tool_effect_reducer";
import AddContributionReducer from "./add_contribution_reducer";
import AppendAgentRunEventReducer from "./append_agent_run_event_reducer";
import AuthorizeNotificationDeliveryReducer from "./authorize_notification_delivery_reducer";
import AuthorizeNotificationDigestReducer from "./authorize_notification_digest_reducer";
import BootstrapOwnerReducer from "./bootstrap_owner_reducer";
import CancelAgentRunReducer from "./cancel_agent_run_reducer";
import CancelDmPromotionReducer from "./cancel_dm_promotion_reducer";
import CancelPlatformOperatorTransferReducer from "./cancel_platform_operator_transfer_reducer";
import CancelWorkspaceDeletionReducer from "./cancel_workspace_deletion_reducer";
import CastPollVoteReducer from "./cast_poll_vote_reducer";
import ClaimAgentRunReducer from "./claim_agent_run_reducer";
import ClaimNotificationDigestsReducer from "./claim_notification_digests_reducer";
import ClaimOutboxJobReducer from "./claim_outbox_job_reducer";
import CompleteAgentRunReducer from "./complete_agent_run_reducer";
import CompleteFileUploadReducer from "./complete_file_upload_reducer";
import CompleteOutboxJobReducer from "./complete_outbox_job_reducer";
import CompleteWorkspaceExportReducer from "./complete_workspace_export_reducer";
import CompleteWorkspaceExportCleanupReducer from "./complete_workspace_export_cleanup_reducer";
import ConfigurePollReducer from "./configure_poll_reducer";
import ConfigureWorkspaceLifecycleReducer from "./configure_workspace_lifecycle_reducer";
import CreateDirectConversationReducer from "./create_direct_conversation_reducer";
import CreateFileUploadReducer from "./create_file_upload_reducer";
import CreateNamedThreadReducer from "./create_named_thread_reducer";
import CreatePostReducer from "./create_post_reducer";
import CreateSpaceReducer from "./create_space_reducer";
import CreateTaskReducer from "./create_task_reducer";
import CreateTypedPostReducer from "./create_typed_post_reducer";
import CreateWorkspaceReducer from "./create_workspace_reducer";
import DecideDmPromotionReducer from "./decide_dm_promotion_reducer";
import DecideToolApprovalReducer from "./decide_tool_approval_reducer";
import DeleteContributionReducer from "./delete_contribution_reducer";
import DeleteDirectMessageReducer from "./delete_direct_message_reducer";
import DeleteFileReducer from "./delete_file_reducer";
import DeletePostReducer from "./delete_post_reducer";
import EditContributionReducer from "./edit_contribution_reducer";
import EditDirectMessageReducer from "./edit_direct_message_reducer";
import EditPostReducer from "./edit_post_reducer";
import ExpireDmPromotionReducer from "./expire_dm_promotion_reducer";
import ExpirePlatformOperatorTransferReducer from "./expire_platform_operator_transfer_reducer";
import ExpirePresenceSessionsReducer from "./expire_presence_sessions_reducer";
import ExpireToolApprovalReducer from "./expire_tool_approval_reducer";
import FinalizeDmPromotionReducer from "./finalize_dm_promotion_reducer";
import FinalizeWorkspaceDeletionFenceReducer from "./finalize_workspace_deletion_fence_reducer";
import HeartbeatAgentRunReducer from "./heartbeat_agent_run_reducer";
import HeartbeatOutboxJobReducer from "./heartbeat_outbox_job_reducer";
import HeartbeatPresenceReducer from "./heartbeat_presence_reducer";
import InstallAgentReducer from "./install_agent_reducer";
import LeaveDirectConversationReducer from "./leave_direct_conversation_reducer";
import MarkDirectReadReducer from "./mark_direct_read_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import MigratePlatformAuthorityReducer from "./migrate_platform_authority_reducer";
import PlaceWorkspaceLegalHoldReducer from "./place_workspace_legal_hold_reducer";
import ProposeDmPromotionReducer from "./propose_dm_promotion_reducer";
import ProposePlatformOperatorTransferReducer from "./propose_platform_operator_transfer_reducer";
import ReconcileAgentToolEffectReducer from "./reconcile_agent_tool_effect_reducer";
import RecordAgentContextContributionReducer from "./record_agent_context_contribution_reducer";
import RecordAgentContextPostReducer from "./record_agent_context_post_reducer";
import RecordDecisionReducer from "./record_decision_reducer";
import RecordFileExtractionReducer from "./record_file_extraction_reducer";
import RecordFileScanOutcomeReducer from "./record_file_scan_outcome_reducer";
import RecordNotificationDigestOutcomeReducer from "./record_notification_digest_outcome_reducer";
import RecordToolOutcomeReducer from "./record_tool_outcome_reducer";
import RecoverOutboxJobReducer from "./recover_outbox_job_reducer";
import RegisterServicePrincipalReducer from "./register_service_principal_reducer";
import RegisterTrustedToolReducer from "./register_trusted_tool_reducer";
import RegisterUserReducer from "./register_user_reducer";
import ReleaseWorkspaceLegalHoldReducer from "./release_workspace_legal_hold_reducer";
import RequestAgentToolCallReducer from "./request_agent_tool_call_reducer";
import RequestSearchRebuildReducer from "./request_search_rebuild_reducer";
import RequestWorkspaceDeletionReducer from "./request_workspace_deletion_reducer";
import RequestWorkspaceExportReducer from "./request_workspace_export_reducer";
import RevokeAgentReducer from "./revoke_agent_reducer";
import SendDirectMessageReducer from "./send_direct_message_reducer";
import SetAgentScopeReducer from "./set_agent_scope_reducer";
import SetAgentToolPolicyReducer from "./set_agent_tool_policy_reducer";
import SetNotificationPreferenceReducer from "./set_notification_preference_reducer";
import SetPollClosedReducer from "./set_poll_closed_reducer";
import SetPostMetadataReducer from "./set_post_metadata_reducer";
import SetPostPersonalStateReducer from "./set_post_personal_state_reducer";
import SetPostPinReducer from "./set_post_pin_reducer";
import SetPostReactionReducer from "./set_post_reaction_reducer";
import SetServiceGrantReducer from "./set_service_grant_reducer";
import SetSpaceMemberReducer from "./set_space_member_reducer";
import SetWorkspaceMemberReducer from "./set_workspace_member_reducer";
import StartAgentRunReducer from "./start_agent_run_reducer";
import UpdateDecisionStatusReducer from "./update_decision_status_reducer";
import UpdateNamedThreadReducer from "./update_named_thread_reducer";
import UpdatePostLifecycleReducer from "./update_post_lifecycle_reducer";
import UpdateTaskStatusReducer from "./update_task_status_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentContextCandidatesRow from "./agent_context_candidates_table";
import AgentWorkQueueRow from "./agent_work_queue_table";
import CurrentUserRow from "./current_user_table";
import FileProcessingPlansRow from "./file_processing_plans_table";
import MyCommandReceiptsRow from "./my_command_receipts_table";
import MyDirectReadStatesRow from "./my_direct_read_states_table";
import MyFileUploadsRow from "./my_file_uploads_table";
import MyNotificationPreferencesRow from "./my_notification_preferences_table";
import MyNotificationsRow from "./my_notifications_table";
import MyPostStatesRow from "./my_post_states_table";
import MyWorkspaceExportsRow from "./my_workspace_exports_table";
import MyWorkspaceLegalHoldsRow from "./my_workspace_legal_holds_table";
import MyWorkspaceLifecyclesRow from "./my_workspace_lifecycles_table";
import MyWorkspaceMembershipsRow from "./my_workspace_memberships_table";
import MyWorkspacesRow from "./my_workspaces_table";
import PendingNotificationDeliveryPlansRow from "./pending_notification_delivery_plans_table";
import PendingNotificationDigestPlansRow from "./pending_notification_digest_plans_table";
import PendingNotificationDigestSchedulesRow from "./pending_notification_digest_schedules_table";
import PendingOutboxWorkRow from "./pending_outbox_work_table";
import PendingPostSearchDocumentsRow from "./pending_post_search_documents_table";
import PendingWorkspaceExportCleanupPlansRow from "./pending_workspace_export_cleanup_plans_table";
import PendingWorkspaceExportPlansRow from "./pending_workspace_export_plans_table";
import VisibleAgentContextManifestsRow from "./visible_agent_context_manifests_table";
import VisibleAgentInstallationsRow from "./visible_agent_installations_table";
import VisibleAgentRunEventsRow from "./visible_agent_run_events_table";
import VisibleAgentRunsRow from "./visible_agent_runs_table";
import VisibleAgentScopesRow from "./visible_agent_scopes_table";
import VisibleAgentToolCallsRow from "./visible_agent_tool_calls_table";
import VisibleAgentToolPoliciesRow from "./visible_agent_tool_policies_table";
import VisibleApprovalsRow from "./visible_approvals_table";
import VisibleAuditLogRow from "./visible_audit_log_table";
import VisibleContributionsRow from "./visible_contributions_table";
import VisibleDecisionsRow from "./visible_decisions_table";
import VisibleDirectConversationsRow from "./visible_direct_conversations_table";
import VisibleDirectMessagesRow from "./visible_direct_messages_table";
import VisibleDirectParticipantsRow from "./visible_direct_participants_table";
import VisibleDirectReplyAncestryRow from "./visible_direct_reply_ancestry_table";
import VisibleDmPromotionConsentsRow from "./visible_dm_promotion_consents_table";
import VisibleDmPromotionProposalsRow from "./visible_dm_promotion_proposals_table";
import VisibleDmPromotionSourcesRow from "./visible_dm_promotion_sources_table";
import VisibleFilesRow from "./visible_files_table";
import VisibleNamedThreadsRow from "./visible_named_threads_table";
import VisiblePollOptionsRow from "./visible_poll_options_table";
import VisiblePollsRow from "./visible_polls_table";
import VisiblePostActivityRow from "./visible_post_activity_table";
import VisiblePostMentionsRow from "./visible_post_mentions_table";
import VisiblePostPinsRow from "./visible_post_pins_table";
import VisiblePostReactionsRow from "./visible_post_reactions_table";
import VisiblePostTagsRow from "./visible_post_tags_table";
import VisiblePostsRow from "./visible_posts_table";
import VisiblePresenceRow from "./visible_presence_table";
import VisibleReplyAncestryRow from "./visible_reply_ancestry_table";
import VisibleSpacesRow from "./visible_spaces_table";
import VisibleTasksRow from "./visible_tasks_table";
import VisibleWorkspaceMembersRow from "./visible_workspace_members_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent_context_candidates: __table({
    name: 'agent_context_candidates',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentContextCandidatesRow),
  agent_work_queue: __table({
    name: 'agent_work_queue',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentWorkQueueRow),
  current_user: __table({
    name: 'current_user',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentUserRow),
  file_processing_plans: __table({
    name: 'file_processing_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, FileProcessingPlansRow),
  my_command_receipts: __table({
    name: 'my_command_receipts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommandReceiptsRow),
  my_direct_read_states: __table({
    name: 'my_direct_read_states',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDirectReadStatesRow),
  my_file_uploads: __table({
    name: 'my_file_uploads',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFileUploadsRow),
  my_notification_preferences: __table({
    name: 'my_notification_preferences',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationPreferencesRow),
  my_notifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  my_post_states: __table({
    name: 'my_post_states',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPostStatesRow),
  my_workspace_exports: __table({
    name: 'my_workspace_exports',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceExportsRow),
  my_workspace_legal_holds: __table({
    name: 'my_workspace_legal_holds',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceLegalHoldsRow),
  my_workspace_lifecycles: __table({
    name: 'my_workspace_lifecycles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceLifecyclesRow),
  my_workspace_memberships: __table({
    name: 'my_workspace_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceMembershipsRow),
  my_workspaces: __table({
    name: 'my_workspaces',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspacesRow),
  pending_notification_delivery_plans: __table({
    name: 'pending_notification_delivery_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingNotificationDeliveryPlansRow),
  pending_notification_digest_plans: __table({
    name: 'pending_notification_digest_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingNotificationDigestPlansRow),
  pending_notification_digest_schedules: __table({
    name: 'pending_notification_digest_schedules',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingNotificationDigestSchedulesRow),
  pending_outbox_work: __table({
    name: 'pending_outbox_work',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingOutboxWorkRow),
  pending_post_search_documents: __table({
    name: 'pending_post_search_documents',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingPostSearchDocumentsRow),
  pending_workspace_export_cleanup_plans: __table({
    name: 'pending_workspace_export_cleanup_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingWorkspaceExportCleanupPlansRow),
  pending_workspace_export_plans: __table({
    name: 'pending_workspace_export_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingWorkspaceExportPlansRow),
  visible_agent_context_manifests: __table({
    name: 'visible_agent_context_manifests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentContextManifestsRow),
  visible_agent_installations: __table({
    name: 'visible_agent_installations',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentInstallationsRow),
  visible_agent_run_events: __table({
    name: 'visible_agent_run_events',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentRunEventsRow),
  visible_agent_runs: __table({
    name: 'visible_agent_runs',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentRunsRow),
  visible_agent_scopes: __table({
    name: 'visible_agent_scopes',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentScopesRow),
  visible_agent_tool_calls: __table({
    name: 'visible_agent_tool_calls',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentToolCallsRow),
  visible_agent_tool_policies: __table({
    name: 'visible_agent_tool_policies',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentToolPoliciesRow),
  visible_approvals: __table({
    name: 'visible_approvals',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleApprovalsRow),
  visible_audit_log: __table({
    name: 'visible_audit_log',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAuditLogRow),
  visible_contributions: __table({
    name: 'visible_contributions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleContributionsRow),
  visible_decisions: __table({
    name: 'visible_decisions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDecisionsRow),
  visible_direct_conversations: __table({
    name: 'visible_direct_conversations',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDirectConversationsRow),
  visible_direct_messages: __table({
    name: 'visible_direct_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDirectMessagesRow),
  visible_direct_participants: __table({
    name: 'visible_direct_participants',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDirectParticipantsRow),
  visible_direct_reply_ancestry: __table({
    name: 'visible_direct_reply_ancestry',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDirectReplyAncestryRow),
  visible_dm_promotion_consents: __table({
    name: 'visible_dm_promotion_consents',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDmPromotionConsentsRow),
  visible_dm_promotion_proposals: __table({
    name: 'visible_dm_promotion_proposals',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDmPromotionProposalsRow),
  visible_dm_promotion_sources: __table({
    name: 'visible_dm_promotion_sources',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDmPromotionSourcesRow),
  visible_files: __table({
    name: 'visible_files',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleFilesRow),
  visible_named_threads: __table({
    name: 'visible_named_threads',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleNamedThreadsRow),
  visible_poll_options: __table({
    name: 'visible_poll_options',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePollOptionsRow),
  visible_polls: __table({
    name: 'visible_polls',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePollsRow),
  visible_post_activity: __table({
    name: 'visible_post_activity',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostActivityRow),
  visible_post_mentions: __table({
    name: 'visible_post_mentions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostMentionsRow),
  visible_post_pins: __table({
    name: 'visible_post_pins',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostPinsRow),
  visible_post_reactions: __table({
    name: 'visible_post_reactions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostReactionsRow),
  visible_post_tags: __table({
    name: 'visible_post_tags',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostTagsRow),
  visible_posts: __table({
    name: 'visible_posts',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostsRow),
  visible_presence: __table({
    name: 'visible_presence',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePresenceRow),
  visible_reply_ancestry: __table({
    name: 'visible_reply_ancestry',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleReplyAncestryRow),
  visible_spaces: __table({
    name: 'visible_spaces',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleSpacesRow),
  visible_tasks: __table({
    name: 'visible_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleTasksRow),
  visible_workspace_members: __table({
    name: 'visible_workspace_members',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorkspaceMembersRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_platform_operator_transfer", AcceptPlatformOperatorTransferReducer),
  __reducerSchema("acquire_agent_tool_effect", AcquireAgentToolEffectReducer),
  __reducerSchema("add_contribution", AddContributionReducer),
  __reducerSchema("append_agent_run_event", AppendAgentRunEventReducer),
  __reducerSchema("authorize_notification_delivery", AuthorizeNotificationDeliveryReducer),
  __reducerSchema("authorize_notification_digest", AuthorizeNotificationDigestReducer),
  __reducerSchema("bootstrap_owner", BootstrapOwnerReducer),
  __reducerSchema("cancel_agent_run", CancelAgentRunReducer),
  __reducerSchema("cancel_dm_promotion", CancelDmPromotionReducer),
  __reducerSchema("cancel_platform_operator_transfer", CancelPlatformOperatorTransferReducer),
  __reducerSchema("cancel_workspace_deletion", CancelWorkspaceDeletionReducer),
  __reducerSchema("cast_poll_vote", CastPollVoteReducer),
  __reducerSchema("claim_agent_run", ClaimAgentRunReducer),
  __reducerSchema("claim_notification_digests", ClaimNotificationDigestsReducer),
  __reducerSchema("claim_outbox_job", ClaimOutboxJobReducer),
  __reducerSchema("complete_agent_run", CompleteAgentRunReducer),
  __reducerSchema("complete_file_upload", CompleteFileUploadReducer),
  __reducerSchema("complete_outbox_job", CompleteOutboxJobReducer),
  __reducerSchema("complete_workspace_export", CompleteWorkspaceExportReducer),
  __reducerSchema("complete_workspace_export_cleanup", CompleteWorkspaceExportCleanupReducer),
  __reducerSchema("configure_poll", ConfigurePollReducer),
  __reducerSchema("configure_workspace_lifecycle", ConfigureWorkspaceLifecycleReducer),
  __reducerSchema("create_direct_conversation", CreateDirectConversationReducer),
  __reducerSchema("create_file_upload", CreateFileUploadReducer),
  __reducerSchema("create_named_thread", CreateNamedThreadReducer),
  __reducerSchema("create_post", CreatePostReducer),
  __reducerSchema("create_space", CreateSpaceReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("create_typed_post", CreateTypedPostReducer),
  __reducerSchema("create_workspace", CreateWorkspaceReducer),
  __reducerSchema("decide_dm_promotion", DecideDmPromotionReducer),
  __reducerSchema("decide_tool_approval", DecideToolApprovalReducer),
  __reducerSchema("delete_contribution", DeleteContributionReducer),
  __reducerSchema("delete_direct_message", DeleteDirectMessageReducer),
  __reducerSchema("delete_file", DeleteFileReducer),
  __reducerSchema("delete_post", DeletePostReducer),
  __reducerSchema("edit_contribution", EditContributionReducer),
  __reducerSchema("edit_direct_message", EditDirectMessageReducer),
  __reducerSchema("edit_post", EditPostReducer),
  __reducerSchema("expire_dm_promotion", ExpireDmPromotionReducer),
  __reducerSchema("expire_platform_operator_transfer", ExpirePlatformOperatorTransferReducer),
  __reducerSchema("expire_presence_sessions", ExpirePresenceSessionsReducer),
  __reducerSchema("expire_tool_approval", ExpireToolApprovalReducer),
  __reducerSchema("finalize_dm_promotion", FinalizeDmPromotionReducer),
  __reducerSchema("finalize_workspace_deletion_fence", FinalizeWorkspaceDeletionFenceReducer),
  __reducerSchema("heartbeat_agent_run", HeartbeatAgentRunReducer),
  __reducerSchema("heartbeat_outbox_job", HeartbeatOutboxJobReducer),
  __reducerSchema("heartbeat_presence", HeartbeatPresenceReducer),
  __reducerSchema("install_agent", InstallAgentReducer),
  __reducerSchema("leave_direct_conversation", LeaveDirectConversationReducer),
  __reducerSchema("mark_direct_read", MarkDirectReadReducer),
  __reducerSchema("mark_notification_read", MarkNotificationReadReducer),
  __reducerSchema("migrate_platform_authority", MigratePlatformAuthorityReducer),
  __reducerSchema("place_workspace_legal_hold", PlaceWorkspaceLegalHoldReducer),
  __reducerSchema("propose_dm_promotion", ProposeDmPromotionReducer),
  __reducerSchema("propose_platform_operator_transfer", ProposePlatformOperatorTransferReducer),
  __reducerSchema("reconcile_agent_tool_effect", ReconcileAgentToolEffectReducer),
  __reducerSchema("record_agent_context_contribution", RecordAgentContextContributionReducer),
  __reducerSchema("record_agent_context_post", RecordAgentContextPostReducer),
  __reducerSchema("record_decision", RecordDecisionReducer),
  __reducerSchema("record_file_extraction", RecordFileExtractionReducer),
  __reducerSchema("record_file_scan_outcome", RecordFileScanOutcomeReducer),
  __reducerSchema("record_notification_digest_outcome", RecordNotificationDigestOutcomeReducer),
  __reducerSchema("record_tool_outcome", RecordToolOutcomeReducer),
  __reducerSchema("recover_outbox_job", RecoverOutboxJobReducer),
  __reducerSchema("register_service_principal", RegisterServicePrincipalReducer),
  __reducerSchema("register_trusted_tool", RegisterTrustedToolReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("release_workspace_legal_hold", ReleaseWorkspaceLegalHoldReducer),
  __reducerSchema("request_agent_tool_call", RequestAgentToolCallReducer),
  __reducerSchema("request_search_rebuild", RequestSearchRebuildReducer),
  __reducerSchema("request_workspace_deletion", RequestWorkspaceDeletionReducer),
  __reducerSchema("request_workspace_export", RequestWorkspaceExportReducer),
  __reducerSchema("revoke_agent", RevokeAgentReducer),
  __reducerSchema("send_direct_message", SendDirectMessageReducer),
  __reducerSchema("set_agent_scope", SetAgentScopeReducer),
  __reducerSchema("set_agent_tool_policy", SetAgentToolPolicyReducer),
  __reducerSchema("set_notification_preference", SetNotificationPreferenceReducer),
  __reducerSchema("set_poll_closed", SetPollClosedReducer),
  __reducerSchema("set_post_metadata", SetPostMetadataReducer),
  __reducerSchema("set_post_personal_state", SetPostPersonalStateReducer),
  __reducerSchema("set_post_pin", SetPostPinReducer),
  __reducerSchema("set_post_reaction", SetPostReactionReducer),
  __reducerSchema("set_service_grant", SetServiceGrantReducer),
  __reducerSchema("set_space_member", SetSpaceMemberReducer),
  __reducerSchema("set_workspace_member", SetWorkspaceMemberReducer),
  __reducerSchema("start_agent_run", StartAgentRunReducer),
  __reducerSchema("update_decision_status", UpdateDecisionStatusReducer),
  __reducerSchema("update_named_thread", UpdateNamedThreadReducer),
  __reducerSchema("update_post_lifecycle", UpdatePostLifecycleReducer),
  __reducerSchema("update_task_status", UpdateTaskStatusReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
