// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptPlatformOperatorTransferReducer from "./accept_platform_operator_transfer_reducer";
import AcquireAgentToolEffectReducer from "./acquire_agent_tool_effect_reducer";
import AddContributionReducer from "./add_contribution_reducer";
import AppendAgentRunEventReducer from "./append_agent_run_event_reducer";
import BootstrapOwnerReducer from "./bootstrap_owner_reducer";
import CancelAgentRunReducer from "./cancel_agent_run_reducer";
import CancelPlatformOperatorTransferReducer from "./cancel_platform_operator_transfer_reducer";
import ClaimAgentRunReducer from "./claim_agent_run_reducer";
import ClaimOutboxJobReducer from "./claim_outbox_job_reducer";
import CompleteAgentRunReducer from "./complete_agent_run_reducer";
import CompleteFileUploadReducer from "./complete_file_upload_reducer";
import CompleteOutboxJobReducer from "./complete_outbox_job_reducer";
import CreateFileUploadReducer from "./create_file_upload_reducer";
import CreateNamedThreadReducer from "./create_named_thread_reducer";
import CreatePostReducer from "./create_post_reducer";
import CreateSpaceReducer from "./create_space_reducer";
import CreateTaskReducer from "./create_task_reducer";
import CreateWorkspaceReducer from "./create_workspace_reducer";
import DecideToolApprovalReducer from "./decide_tool_approval_reducer";
import DeleteContributionReducer from "./delete_contribution_reducer";
import DeleteFileReducer from "./delete_file_reducer";
import DeletePostReducer from "./delete_post_reducer";
import EditContributionReducer from "./edit_contribution_reducer";
import EditPostReducer from "./edit_post_reducer";
import ExpirePlatformOperatorTransferReducer from "./expire_platform_operator_transfer_reducer";
import ExpireToolApprovalReducer from "./expire_tool_approval_reducer";
import HeartbeatAgentRunReducer from "./heartbeat_agent_run_reducer";
import HeartbeatOutboxJobReducer from "./heartbeat_outbox_job_reducer";
import InstallAgentReducer from "./install_agent_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import MigratePlatformAuthorityReducer from "./migrate_platform_authority_reducer";
import ProposePlatformOperatorTransferReducer from "./propose_platform_operator_transfer_reducer";
import ReconcileAgentToolEffectReducer from "./reconcile_agent_tool_effect_reducer";
import RecordAgentContextContributionReducer from "./record_agent_context_contribution_reducer";
import RecordAgentContextPostReducer from "./record_agent_context_post_reducer";
import RecordDecisionReducer from "./record_decision_reducer";
import RecordFileExtractionReducer from "./record_file_extraction_reducer";
import RecordFileScanOutcomeReducer from "./record_file_scan_outcome_reducer";
import RecordToolOutcomeReducer from "./record_tool_outcome_reducer";
import RegisterServicePrincipalReducer from "./register_service_principal_reducer";
import RegisterTrustedToolReducer from "./register_trusted_tool_reducer";
import RegisterUserReducer from "./register_user_reducer";
import RequestAgentToolCallReducer from "./request_agent_tool_call_reducer";
import RevokeAgentReducer from "./revoke_agent_reducer";
import SetAgentScopeReducer from "./set_agent_scope_reducer";
import SetAgentToolPolicyReducer from "./set_agent_tool_policy_reducer";
import SetServiceGrantReducer from "./set_service_grant_reducer";
import SetSpaceMemberReducer from "./set_space_member_reducer";
import SetWorkspaceMemberReducer from "./set_workspace_member_reducer";
import StartAgentRunReducer from "./start_agent_run_reducer";
import UpdateDecisionStatusReducer from "./update_decision_status_reducer";
import UpdateNamedThreadReducer from "./update_named_thread_reducer";
import UpdateTaskStatusReducer from "./update_task_status_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentContextCandidatesRow from "./agent_context_candidates_table";
import AgentWorkQueueRow from "./agent_work_queue_table";
import CurrentUserRow from "./current_user_table";
import FileProcessingPlansRow from "./file_processing_plans_table";
import MyCommandReceiptsRow from "./my_command_receipts_table";
import MyFileUploadsRow from "./my_file_uploads_table";
import MyNotificationsRow from "./my_notifications_table";
import MyWorkspaceMembershipsRow from "./my_workspace_memberships_table";
import MyWorkspacesRow from "./my_workspaces_table";
import PendingOutboxWorkRow from "./pending_outbox_work_table";
import PendingPostSearchDocumentsRow from "./pending_post_search_documents_table";
import VisibleAgentContextManifestsRow from "./visible_agent_context_manifests_table";
import VisibleAgentInstallationsRow from "./visible_agent_installations_table";
import VisibleAgentRunEventsRow from "./visible_agent_run_events_table";
import VisibleAgentRunsRow from "./visible_agent_runs_table";
import VisibleAgentScopesRow from "./visible_agent_scopes_table";
import VisibleAgentToolCallsRow from "./visible_agent_tool_calls_table";
import VisibleAgentToolPoliciesRow from "./visible_agent_tool_policies_table";
import VisibleApprovalsRow from "./visible_approvals_table";
import VisibleAuditLogRow from "./visible_audit_log_table";
import VisibleContributionsRow from "./visible_contributions_table";
import VisibleDecisionsRow from "./visible_decisions_table";
import VisibleFilesRow from "./visible_files_table";
import VisibleNamedThreadsRow from "./visible_named_threads_table";
import VisiblePostsRow from "./visible_posts_table";
import VisibleReplyAncestryRow from "./visible_reply_ancestry_table";
import VisibleSpacesRow from "./visible_spaces_table";
import VisibleTasksRow from "./visible_tasks_table";
import VisibleWorkspaceMembersRow from "./visible_workspace_members_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agent_context_candidates: __table({
    name: 'agent_context_candidates',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentContextCandidatesRow),
  agent_work_queue: __table({
    name: 'agent_work_queue',
    indexes: [
    ],
    constraints: [
    ],
  }, AgentWorkQueueRow),
  current_user: __table({
    name: 'current_user',
    indexes: [
    ],
    constraints: [
    ],
  }, CurrentUserRow),
  file_processing_plans: __table({
    name: 'file_processing_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, FileProcessingPlansRow),
  my_command_receipts: __table({
    name: 'my_command_receipts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommandReceiptsRow),
  my_file_uploads: __table({
    name: 'my_file_uploads',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFileUploadsRow),
  my_notifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  my_workspace_memberships: __table({
    name: 'my_workspace_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceMembershipsRow),
  my_workspaces: __table({
    name: 'my_workspaces',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspacesRow),
  pending_outbox_work: __table({
    name: 'pending_outbox_work',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingOutboxWorkRow),
  pending_post_search_documents: __table({
    name: 'pending_post_search_documents',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingPostSearchDocumentsRow),
  visible_agent_context_manifests: __table({
    name: 'visible_agent_context_manifests',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentContextManifestsRow),
  visible_agent_installations: __table({
    name: 'visible_agent_installations',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentInstallationsRow),
  visible_agent_run_events: __table({
    name: 'visible_agent_run_events',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentRunEventsRow),
  visible_agent_runs: __table({
    name: 'visible_agent_runs',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentRunsRow),
  visible_agent_scopes: __table({
    name: 'visible_agent_scopes',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentScopesRow),
  visible_agent_tool_calls: __table({
    name: 'visible_agent_tool_calls',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentToolCallsRow),
  visible_agent_tool_policies: __table({
    name: 'visible_agent_tool_policies',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAgentToolPoliciesRow),
  visible_approvals: __table({
    name: 'visible_approvals',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleApprovalsRow),
  visible_audit_log: __table({
    name: 'visible_audit_log',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleAuditLogRow),
  visible_contributions: __table({
    name: 'visible_contributions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleContributionsRow),
  visible_decisions: __table({
    name: 'visible_decisions',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleDecisionsRow),
  visible_files: __table({
    name: 'visible_files',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleFilesRow),
  visible_named_threads: __table({
    name: 'visible_named_threads',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleNamedThreadsRow),
  visible_posts: __table({
    name: 'visible_posts',
    indexes: [
    ],
    constraints: [
    ],
  }, VisiblePostsRow),
  visible_reply_ancestry: __table({
    name: 'visible_reply_ancestry',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleReplyAncestryRow),
  visible_spaces: __table({
    name: 'visible_spaces',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleSpacesRow),
  visible_tasks: __table({
    name: 'visible_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleTasksRow),
  visible_workspace_members: __table({
    name: 'visible_workspace_members',
    indexes: [
    ],
    constraints: [
    ],
  }, VisibleWorkspaceMembersRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_platform_operator_transfer", AcceptPlatformOperatorTransferReducer),
  __reducerSchema("acquire_agent_tool_effect", AcquireAgentToolEffectReducer),
  __reducerSchema("add_contribution", AddContributionReducer),
  __reducerSchema("append_agent_run_event", AppendAgentRunEventReducer),
  __reducerSchema("bootstrap_owner", BootstrapOwnerReducer),
  __reducerSchema("cancel_agent_run", CancelAgentRunReducer),
  __reducerSchema("cancel_platform_operator_transfer", CancelPlatformOperatorTransferReducer),
  __reducerSchema("claim_agent_run", ClaimAgentRunReducer),
  __reducerSchema("claim_outbox_job", ClaimOutboxJobReducer),
  __reducerSchema("complete_agent_run", CompleteAgentRunReducer),
  __reducerSchema("complete_file_upload", CompleteFileUploadReducer),
  __reducerSchema("complete_outbox_job", CompleteOutboxJobReducer),
  __reducerSchema("create_file_upload", CreateFileUploadReducer),
  __reducerSchema("create_named_thread", CreateNamedThreadReducer),
  __reducerSchema("create_post", CreatePostReducer),
  __reducerSchema("create_space", CreateSpaceReducer),
  __reducerSchema("create_task", CreateTaskReducer),
  __reducerSchema("create_workspace", CreateWorkspaceReducer),
  __reducerSchema("decide_tool_approval", DecideToolApprovalReducer),
  __reducerSchema("delete_contribution", DeleteContributionReducer),
  __reducerSchema("delete_file", DeleteFileReducer),
  __reducerSchema("delete_post", DeletePostReducer),
  __reducerSchema("edit_contribution", EditContributionReducer),
  __reducerSchema("edit_post", EditPostReducer),
  __reducerSchema("expire_platform_operator_transfer", ExpirePlatformOperatorTransferReducer),
  __reducerSchema("expire_tool_approval", ExpireToolApprovalReducer),
  __reducerSchema("heartbeat_agent_run", HeartbeatAgentRunReducer),
  __reducerSchema("heartbeat_outbox_job", HeartbeatOutboxJobReducer),
  __reducerSchema("install_agent", InstallAgentReducer),
  __reducerSchema("mark_notification_read", MarkNotificationReadReducer),
  __reducerSchema("migrate_platform_authority", MigratePlatformAuthorityReducer),
  __reducerSchema("propose_platform_operator_transfer", ProposePlatformOperatorTransferReducer),
  __reducerSchema("reconcile_agent_tool_effect", ReconcileAgentToolEffectReducer),
  __reducerSchema("record_agent_context_contribution", RecordAgentContextContributionReducer),
  __reducerSchema("record_agent_context_post", RecordAgentContextPostReducer),
  __reducerSchema("record_decision", RecordDecisionReducer),
  __reducerSchema("record_file_extraction", RecordFileExtractionReducer),
  __reducerSchema("record_file_scan_outcome", RecordFileScanOutcomeReducer),
  __reducerSchema("record_tool_outcome", RecordToolOutcomeReducer),
  __reducerSchema("register_service_principal", RegisterServicePrincipalReducer),
  __reducerSchema("register_trusted_tool", RegisterTrustedToolReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("request_agent_tool_call", RequestAgentToolCallReducer),
  __reducerSchema("revoke_agent", RevokeAgentReducer),
  __reducerSchema("set_agent_scope", SetAgentScopeReducer),
  __reducerSchema("set_agent_tool_policy", SetAgentToolPolicyReducer),
  __reducerSchema("set_service_grant", SetServiceGrantReducer),
  __reducerSchema("set_space_member", SetSpaceMemberReducer),
  __reducerSchema("set_workspace_member", SetWorkspaceMemberReducer),
  __reducerSchema("start_agent_run", StartAgentRunReducer),
  __reducerSchema("update_decision_status", UpdateDecisionStatusReducer),
  __reducerSchema("update_named_thread", UpdateNamedThreadReducer),
  __reducerSchema("update_task_status", UpdateTaskStatusReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
