// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workspaceId: __t.option(__t.uuid()).name("workspace_id"),
  operation: __t.string(),
  clientRequestId: __t.uuid().name("client_request_id"),
  resultType: __t.string().name("result_type"),
  resultId: __t.uuid().name("result_id"),
  committedAt: __t.timestamp().name("committed_at"),
});
