// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  fileId: __t.uuid().name("file_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  sourceKey: __t.string().name("source_key"),
  completed: __t.bool(),
  expiresAt: __t.timestamp().name("expires_at"),
  createdAt: __t.timestamp().name("created_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
