// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FileSecurityState,
} from "./types";


export default __t.row({
  uploadId: __t.uuid().name("upload_id"),
  fileId: __t.uuid().name("file_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  uploaderIdentity: __t.identity().name("uploader_identity"),
  sourceKey: __t.string().name("source_key"),
  fileName: __t.string().name("file_name"),
  declaredType: __t.string().name("declared_type"),
  declaredSizeBytes: __t.u64().name("declared_size_bytes"),
  checksumSha256: __t.string().name("checksum_sha_256"),
  expiresAt: __t.timestamp().name("expires_at"),
  completed: __t.bool(),
  get fileState() {
    return FileSecurityState.name("file_state");
  },
  fileRevision: __t.u64().name("file_revision"),
});
