// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WorkspaceRole,
} from "./types";


export default __t.row({
  workspaceId: __t.uuid().name("workspace_id"),
  get role() {
    return WorkspaceRole;
  },
  membershipEpoch: __t.u64().name("membership_epoch"),
  userAuthzEpoch: __t.u64().name("user_authz_epoch"),
  lifecycleEpoch: __t.u64().name("lifecycle_epoch"),
  canRead: __t.bool().name("can_read"),
  canWrite: __t.bool().name("can_write"),
  canManageMembers: __t.bool().name("can_manage_members"),
  canManageWorkspace: __t.bool().name("can_manage_workspace"),
  canManageAgents: __t.bool().name("can_manage_agents"),
  canRunAgents: __t.bool().name("can_run_agents"),
});
