// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  membershipEpoch: __t.u64().name("membership_epoch"),
  canRead: __t.bool().name("can_read"),
  canWrite: __t.bool().name("can_write"),
  canRunAgents: __t.bool().name("can_run_agents"),
});
