// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FileSecurityState,
} from "./types";


export default __t.row({
  fileId: __t.uuid().name("file_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  fileName: __t.string().name("file_name"),
  objectKey: __t.string().name("object_key"),
  objectVersion: __t.string().name("object_version"),
  checksumSha256: __t.string().name("checksum_sha_256"),
  detectedType: __t.string().name("detected_type"),
  sizeBytes: __t.u64().name("size_bytes"),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
});
