// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationDeliveryMode,
} from "./types";


export default __t.row({
  key: __t.string(),
  identity: __t.identity(),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.option(__t.uuid()).name("space_id"),
  get directMode() {
    return NotificationDeliveryMode.name("direct_mode");
  },
  get importantMode() {
    return NotificationDeliveryMode.name("important_mode");
  },
  get ambientMode() {
    return NotificationDeliveryMode.name("ambient_mode");
  },
  muteStartLocalMinute: __t.option(__t.u16()).name("mute_start_local_minute"),
  muteEndLocalMinute: __t.option(__t.u16()).name("mute_end_local_minute"),
  timeZone: __t.string().name("time_zone"),
  digestLocalMinute: __t.u16().name("digest_local_minute"),
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
