// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationKind,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  get kind() {
    return NotificationKind;
  },
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  summary: __t.string(),
  readAt: __t.option(__t.timestamp()).name("read_at"),
  createdAt: __t.timestamp().name("created_at"),
});
