// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  postId: __t.uuid().name("post_id"),
  following: __t.bool(),
  bookmarked: __t.bool(),
  unread: __t.bool(),
  lastReadSequence: __t.u64().name("last_read_sequence"),
  readAt: __t.option(__t.timestamp()).name("read_at"),
});
