// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WorkspaceLifecycleState,
} from "./types";


export default __t.row({
  workspaceId: __t.uuid().name("workspace_id"),
  get state() {
    return WorkspaceLifecycleState;
  },
  lifecycleEpoch: __t.u64().name("lifecycle_epoch"),
  deletedContentRetentionDays: __t.option(__t.u32()).name("deleted_content_retention_days"),
  deletionGraceDays: __t.option(__t.u16()).name("deletion_grace_days"),
  deletionExecuteAfter: __t.option(__t.timestamp()).name("deletion_execute_after"),
  revision: __t.u64(),
});
