// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WorkspaceExportState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  get state() {
    return WorkspaceExportState;
  },
  artifactKey: __t.string().name("artifact_key"),
  contentHash: __t.string().name("content_hash"),
  sizeBytes: __t.u64().name("size_bytes"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
  failureReason: __t.string().name("failure_reason"),
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
