// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WorkspaceLegalHoldState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  get state() {
    return WorkspaceLegalHoldState;
  },
  placedAt: __t.timestamp().name("placed_at"),
  releasedAt: __t.option(__t.timestamp()).name("released_at"),
  revision: __t.u64(),
});
