// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OutboxState,
} from "./types";


export default __t.row({
  jobId: __t.uuid().name("job_id"),
  exportId: __t.uuid().name("export_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  lifecycleEpoch: __t.u64().name("lifecycle_epoch"),
  workspaceRevision: __t.u64().name("workspace_revision"),
  exportRevision: __t.u64().name("export_revision"),
  reconcileOnly: __t.bool().name("reconcile_only"),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  workerSlotId: __t.string().name("worker_slot_id"),
  leaseGeneration: __t.u64().name("lease_generation"),
});
