// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OutboxState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  kind: __t.string(),
  effectKey: __t.string().name("effect_key"),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  aclRevision: __t.option(__t.u64()).name("acl_revision"),
  intentId: __t.option(__t.uuid()).name("intent_id"),
  recipientId: __t.option(__t.identity()).name("recipient_id"),
  channel: __t.string(),
  authorizationEpoch: __t.option(__t.u64()).name("authorization_epoch"),
  minimalMessage: __t.string().name("minimal_message"),
  payloadResourceId: __t.option(__t.uuid()).name("payload_resource_id"),
  rebuildId: __t.option(__t.uuid()).name("rebuild_id"),
  generation: __t.option(__t.u64()),
  fileId: __t.option(__t.uuid()).name("file_id"),
  version: __t.option(__t.u64()),
  runId: __t.option(__t.uuid()).name("run_id"),
  createdAt: __t.timestamp().name("created_at"),
  nextAttemptAt: __t.timestamp().name("next_attempt_at"),
  attempt: __t.u32(),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  workerSlotId: __t.string().name("worker_slot_id"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  leaseGeneration: __t.u64().name("lease_generation"),
  lastError: __t.string().name("last_error"),
});
