// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationDigestClaimState,
} from "./types";


export default __t.row({
  scheduleId: __t.uuid().name("schedule_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  channel: __t.string(),
  timeZone: __t.string().name("time_zone"),
  digestLocalMinute: __t.u16().name("digest_local_minute"),
  preferenceRevision: __t.u64().name("preference_revision"),
  digestRevision: __t.u64().name("digest_revision"),
  lastOccurrenceLocalDate: __t.string().name("last_occurrence_local_date"),
  activeClaimLocalDate: __t.string().name("active_claim_local_date"),
  activeClaimScheduledFor: __t.option(__t.timestamp()).name("active_claim_scheduled_for"),
  get activeClaimState() {
    return __t.option(NotificationDigestClaimState).name("active_claim_state");
  },
  activeClaimPreferenceRevision: __t.option(__t.u64()).name("active_claim_preference_revision"),
  activeClaimDigestRevision: __t.option(__t.u64()).name("active_claim_digest_revision"),
  activeClaimLeaseUntil: __t.option(__t.timestamp()).name("active_claim_lease_until"),
  activeClaimNextAttemptAt: __t.option(__t.timestamp()).name("active_claim_next_attempt_at"),
});
