// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OutboxState,
} from "./types";


export default __t.row({
  jobId: __t.uuid().name("job_id"),
  effectKey: __t.string().name("effect_key"),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  aclRevision: __t.u64().name("acl_revision"),
  title: __t.string(),
  body: __t.string(),
  tombstone: __t.bool(),
  allowedIdentities: __t.array(__t.identity()).name("allowed_identities"),
  get state() {
    return OutboxState;
  },
  leaseGeneration: __t.u64().name("lease_generation"),
});
