// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  claimId: __t.uuid().name("claim_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  channel: __t.string(),
  scheduleId: __t.uuid().name("schedule_id"),
  localDate: __t.string().name("local_date"),
  scheduledFor: __t.timestamp().name("scheduled_for"),
  preferenceRevision: __t.u64().name("preference_revision"),
  digestRevision: __t.u64().name("digest_revision"),
  authorizationEpoch: __t.u64().name("authorization_epoch"),
  workerSlotId: __t.string().name("worker_slot_id"),
  leaseGeneration: __t.u64().name("lease_generation"),
  reconcileFirst: __t.bool().name("reconcile_first"),
  decision: __t.string(),
  suppressionCode: __t.string().name("suppression_code"),
  body: __t.string(),
  itemCount: __t.u16().name("item_count"),
  permitExpiresAt: __t.option(__t.timestamp()).name("permit_expires_at"),
});
