// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  NotificationDeliveryState,
} from "./types";


export default __t.row({
  jobId: __t.uuid().name("job_id"),
  notificationId: __t.uuid().name("notification_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  channel: __t.string(),
  get deliveryState() {
    return NotificationDeliveryState.name("delivery_state");
  },
  suppressionReason: __t.string().name("suppression_reason"),
  groupKey: __t.string().name("group_key"),
  groupRevision: __t.u64().name("group_revision"),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  membershipEpoch: __t.u64().name("membership_epoch"),
  preferenceRevision: __t.u64().name("preference_revision"),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  workerSlotId: __t.string().name("worker_slot_id"),
  leaseGeneration: __t.u64().name("lease_generation"),
  permitExpiresAt: __t.option(__t.timestamp()).name("permit_expires_at"),
});
