// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OutboxState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  effectKey: __t.string().name("effect_key"),
  get state() {
    return OutboxState;
  },
  kind: __t.string(),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  expiresAt: __t.timestamp().name("expires_at"),
  attempt: __t.u32(),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  leaseGeneration: __t.u64().name("lease_generation"),
  nextAttemptAt: __t.timestamp().name("next_attempt_at"),
  lastError: __t.string().name("last_error"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
