// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ToolCallState,
} from "./types";

export default {
  toolCallId: __t.uuid(),
  leaseGeneration: __t.u64(),
  normalizedArgsHash: __t.string(),
  get outcome() {
    return ToolCallState;
  },
  resultSummary: __t.string(),
};
