// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  runId: __t.uuid().name("run_id"),
  providerSequence: __t.u64().name("provider_sequence"),
  leaseGeneration: __t.u64().name("lease_generation"),
  authorizationEpoch: __t.u64().name("authorization_epoch"),
  requestId: __t.string().name("request_id"),
  inputFingerprint: __t.string().name("input_fingerprint"),
  canonicalInput: __t.string().name("canonical_input"),
  inputBytes: __t.u64().name("input_bytes"),
  contextBindingHash: __t.string().name("context_binding_hash"),
  contextJson: __t.string().name("context_json"),
  createdAt: __t.timestamp().name("created_at"),
});
