// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  jobId: __t.uuid().name("job_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  fileId: __t.uuid().name("file_id"),
  fileRevision: __t.u64().name("file_revision"),
  kind: __t.string(),
  outcome: __t.string(),
});
