// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.uuid().name("run_id"),
  leaseGeneration: __t.u64().name("lease_generation"),
  sequence: __t.u64(),
  outputTokens: __t.u64().name("output_tokens"),
  costMicros: __t.u64().name("cost_micros"),
  toolCalls: __t.u32().name("tool_calls"),
  toolResultsJson: __t.string().name("tool_results_json"),
  providerInputBytes: __t.u64().name("provider_input_bytes"),
  pendingStepJson: __t.string().name("pending_step_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
