// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  claimId: __t.uuid().name("claim_id"),
  generation: __t.u64(),
  workspaceId: __t.uuid().name("workspace_id"),
  fileId: __t.uuid().name("file_id"),
  fileRevision: __t.u64().name("file_revision"),
  key: __t.string(),
  objectVersionTag: __t.string().name("object_version_tag"),
});
