// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  WorkerEffectState,
} from "./types";


export default __t.row({
  effectKey: __t.string().name("effect_key"),
  identityFingerprint: __t.string().name("identity_fingerprint"),
  payloadFingerprint: __t.string().name("payload_fingerprint"),
  workspaceId: __t.uuid().name("workspace_id"),
  authorityKind: __t.string().name("authority_kind"),
  get state() {
    return WorkerEffectState;
  },
  ownerIdentity: __t.identity().name("owner_identity"),
  ownerId: __t.string().name("owner_id"),
  ownerGeneration: __t.u64().name("owner_generation"),
  leaseExpiresAtMillis: __t.u64().name("lease_expires_at_millis"),
  providerReference: __t.string().name("provider_reference"),
  resultJson: __t.string().name("result_json"),
  updatedAt: __t.timestamp().name("updated_at"),
});
