// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ToolEffectClass,
  ApprovalState,
} from "./types";


export default __t.row({
  approvalId: __t.uuid().name("approval_id"),
  nonceHash: __t.string().name("nonce_hash"),
  runId: __t.uuid().name("run_id"),
  callId: __t.string().name("call_id"),
  toolName: __t.string().name("tool_name"),
  toolVersion: __t.string().name("tool_version"),
  argumentsHash: __t.string().name("arguments_hash"),
  get effectClass() {
    return ToolEffectClass.name("effect_class");
  },
  effectKey: __t.string().name("effect_key"),
  expiresAt: __t.timestamp().name("expires_at"),
  get state() {
    return ApprovalState;
  },
});
