// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentRunState,
} from "./types";


export default __t.row({
  runId: __t.uuid().name("run_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  authorizationEpoch: __t.u64().name("authorization_epoch"),
  currentAuthorizationEpoch: __t.u64().name("current_authorization_epoch"),
  installationEnabled: __t.bool().name("installation_enabled"),
  cancelRequested: __t.bool().name("cancel_requested"),
  leaseGeneration: __t.u64().name("lease_generation"),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  executionRequestId: __t.string().name("execution_request_id"),
  maxContextBytes: __t.u64().name("max_context_bytes"),
  maxOutputTokens: __t.u64().name("max_output_tokens"),
  maxToolCalls: __t.u32().name("max_tool_calls"),
  maxCostMicros: __t.u64().name("max_cost_micros"),
  maxOutputBytes: __t.u64().name("max_output_bytes"),
  maxToolResultBytes: __t.u64().name("max_tool_result_bytes"),
  maxTotalToolResultBytes: __t.u64().name("max_total_tool_result_bytes"),
  maxProviderInputBytes: __t.u64().name("max_provider_input_bytes"),
  maxTotalProviderInputBytes: __t.u64().name("max_total_provider_input_bytes"),
});
