// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  WorkspaceRole,
} from "./types";

export default {
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get role() {
    return WorkspaceRole;
  },
  active: __t.bool(),
  expectedAuthzEpoch: __t.u64(),
  clientRequestId: __t.uuid(),
};
