// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `AgentCapability`.
export const AgentCapability = __t.enum("AgentCapability", {
  ReadSpace: __t.unit(),
  ReadHistory: __t.unit(),
  WriteContribution: __t.unit(),
  UseReadTool: __t.unit(),
  UseExternalTool: __t.unit(),
});
export type AgentCapability = __Infer<typeof AgentCapability>;

export const AgentContextCandidate = __t.object("AgentContextCandidate", {
  runId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentContextCandidate = __Infer<typeof AgentContextCandidate>;

export const AgentContextContributionInput = __t.object("AgentContextContributionInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  contributionId: __t.uuid(),
  expectedRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
});
export type AgentContextContributionInput = __Infer<typeof AgentContextContributionInput>;

export const AgentContextManifest = __t.object("AgentContextManifest", {
  id: __t.uuid(),
  runId: __t.uuid(),
  runResourceKey: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
  policyVersion: __t.u32(),
  createdAt: __t.timestamp(),
});
export type AgentContextManifest = __Infer<typeof AgentContextManifest>;

export const AgentContextPostInput = __t.object("AgentContextPostInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  postId: __t.uuid(),
  expectedRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
});
export type AgentContextPostInput = __Infer<typeof AgentContextPostInput>;

export const AgentInstallation = __t.object("AgentInstallation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  secretRef: __t.string(),
  enabled: __t.bool(),
  authzEpoch: __t.u64(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  maxAttempts: __t.u32(),
  maxAgeSeconds: __t.u32(),
  installedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentInstallation = __Infer<typeof AgentInstallation>;

export const AgentRun = __t.object("AgentRun", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  installationId: __t.uuid(),
  spaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  initiatedBy: __t.identity(),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  installationEpoch: __t.u64(),
  membershipEpoch: __t.u64(),
  attempt: __t.u32(),
  cancelRequested: __t.bool(),
  leaseOwner: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  expiresAt: __t.timestamp(),
  nextEventSequence: __t.u64(),
  promptSummary: __t.string(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
  finalContributionId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentRun = __Infer<typeof AgentRun>;

export const AgentRunEvent = __t.object("AgentRunEvent", {
  id: __t.uuid(),
  runId: __t.uuid(),
  sequence: __t.u64(),
  runSequenceKey: __t.string(),
  kind: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentRunEvent = __Infer<typeof AgentRunEvent>;

// The tagged union or sum type for the algebraic type `AgentRunState`.
export const AgentRunState = __t.enum("AgentRunState", {
  Queued: __t.unit(),
  Authorizing: __t.unit(),
  CollectingContext: __t.unit(),
  Running: __t.unit(),
  AwaitingApproval: __t.unit(),
  ExecutingTool: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  Canceled: __t.unit(),
  Expired: __t.unit(),
  Revoked: __t.unit(),
});
export type AgentRunState = __Infer<typeof AgentRunState>;

export const AgentScope = __t.object("AgentScope", {
  key: __t.string(),
  installationId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get capability() {
    return AgentCapability;
  },
  enabled: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentScope = __Infer<typeof AgentScope>;

export const AgentToolCall = __t.object("AgentToolCall", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  policyKey: __t.string(),
  policyRevision: __t.u64(),
  get effectClass() {
    return ToolEffectClass;
  },
  normalizedArgsHash: __t.string(),
  effectKey: __t.string(),
  requiresApproval: __t.bool(),
  get state() {
    return ToolCallState;
  },
  resultSummary: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentToolCall = __Infer<typeof AgentToolCall>;

export const AgentToolCallInput = __t.object("AgentToolCallInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  expectedVersion: __t.u64(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  normalizedArgsHash: __t.string(),
  approvalNonceHash: __t.string(),
  clientRequestId: __t.uuid(),
});
export type AgentToolCallInput = __Infer<typeof AgentToolCallInput>;

export const AgentToolPolicy = __t.object("AgentToolPolicy", {
  key: __t.string(),
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  trustedToolRevision: __t.u64(),
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentToolPolicy = __Infer<typeof AgentToolPolicy>;

export const ApprovalRequest = __t.object("ApprovalRequest", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolCallId: __t.uuid(),
  normalizedArgsHash: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  nonceHash: __t.string(),
  get state() {
    return ApprovalState;
  },
  requestedByService: __t.identity(),
  decidedBy: __t.option(__t.identity()),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  decidedAt: __t.option(__t.timestamp()),
});
export type ApprovalRequest = __Infer<typeof ApprovalRequest>;

// The tagged union or sum type for the algebraic type `ApprovalState`.
export const ApprovalState = __t.enum("ApprovalState", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
  Expired: __t.unit(),
  Consumed: __t.unit(),
});
export type ApprovalState = __Infer<typeof ApprovalState>;

export const AuditLog = __t.object("AuditLog", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  actorIdentity: __t.identity(),
  effectivePrincipal: __t.string(),
  action: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  requestId: __t.uuid(),
  policyVersion: __t.u32(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditLog = __Infer<typeof AuditLog>;

export const AuthPolicy = __t.object("AuthPolicy", {
  singleton: __t.u8(),
  issuer: __t.string(),
  audience: __t.string(),
  configuredBy: __t.identity(),
  configuredAt: __t.timestamp(),
});
export type AuthPolicy = __Infer<typeof AuthPolicy>;

export const BootstrapAuthority = __t.object("BootstrapAuthority", {
  singleton: __t.u8(),
  issuer: __t.string(),
  audience: __t.string(),
  ownerSubject: __t.string(),
  consumed: __t.bool(),
  configuredAt: __t.timestamp(),
});
export type BootstrapAuthority = __Infer<typeof BootstrapAuthority>;

export const CommandReceipt = __t.object("CommandReceipt", {
  key: __t.string(),
  actorIdentity: __t.identity(),
  workspaceId: __t.option(__t.uuid()),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  inputHash: __t.string(),
  resultType: __t.string(),
  resultId: __t.uuid(),
  committedAt: __t.timestamp(),
});
export type CommandReceipt = __Infer<typeof CommandReceipt>;

export const CompleteAgentRunInput = __t.object("CompleteAgentRunInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  expectedVersion: __t.u64(),
  succeeded: __t.bool(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
});
export type CompleteAgentRunInput = __Infer<typeof CompleteAgentRunInput>;

export const ConfigurePollInput = __t.object("ConfigurePollInput", {
  postId: __t.uuid(),
  options: __t.array(__t.string()),
  allowsMultiple: __t.bool(),
  expectedPostRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type ConfigurePollInput = __Infer<typeof ConfigurePollInput>;

export const ConfigureWorkspaceLifecycleInput = __t.object("ConfigureWorkspaceLifecycleInput", {
  workspaceId: __t.uuid(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type ConfigureWorkspaceLifecycleInput = __Infer<typeof ConfigureWorkspaceLifecycleInput>;

export const Contribution = __t.object("Contribution", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.uuid(),
  authorIdentity: __t.identity(),
  agentInstallationId: __t.option(__t.uuid()),
  agentRunId: __t.option(__t.uuid()),
  parentContributionId: __t.option(__t.uuid()),
  get kind() {
    return ContributionKind;
  },
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Contribution = __Infer<typeof Contribution>;

// The tagged union or sum type for the algebraic type `ContributionKind`.
export const ContributionKind = __t.enum("ContributionKind", {
  Message: __t.unit(),
  Update: __t.unit(),
  Summary: __t.unit(),
  AgentOutput: __t.unit(),
});
export type ContributionKind = __Infer<typeof ContributionKind>;

export const CreateDirectConversationInput = __t.object("CreateDirectConversationInput", {
  workspaceId: __t.uuid(),
  participants: __t.array(__t.identity()),
  clientRequestId: __t.uuid(),
});
export type CreateDirectConversationInput = __Infer<typeof CreateDirectConversationInput>;

export const CreateTypedPostInput = __t.object("CreateTypedPostInput", {
  spaceId: __t.uuid(),
  title: __t.string(),
  body: __t.string(),
  get kind() {
    return PostKind;
  },
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  tags: __t.array(__t.string()),
  mentions: __t.array(__t.identity()),
  clientRequestId: __t.uuid(),
});
export type CreateTypedPostInput = __Infer<typeof CreateTypedPostInput>;

export const CurrentPresence = __t.object("CurrentPresence", {
  key: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get status() {
    return PresenceStatus;
  },
  expiresAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CurrentPresence = __Infer<typeof CurrentPresence>;

export const DecisionRecord = __t.object("DecisionRecord", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.uuid(),
  title: __t.string(),
  rationale: __t.string(),
  get status() {
    return DecisionStatus;
  },
  supersedesDecisionId: __t.option(__t.uuid()),
  createdBy: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DecisionRecord = __Infer<typeof DecisionRecord>;

// The tagged union or sum type for the algebraic type `DecisionStatus`.
export const DecisionStatus = __t.enum("DecisionStatus", {
  Proposed: __t.unit(),
  Accepted: __t.unit(),
  Rejected: __t.unit(),
  Superseded: __t.unit(),
});
export type DecisionStatus = __Infer<typeof DecisionStatus>;

export const DirectConversation = __t.object("DirectConversation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  createdBy: __t.identity(),
  nextSequence: __t.u64(),
  revision: __t.u64(),
  deactivatedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DirectConversation = __Infer<typeof DirectConversation>;

export const DirectMessage = __t.object("DirectMessage", {
  id: __t.uuid(),
  sequenceKey: __t.string(),
  conversationId: __t.uuid(),
  authorIdentity: __t.identity(),
  workspaceId: __t.uuid(),
  sequence: __t.u64(),
  parentMessageId: __t.option(__t.uuid()),
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
  deletedAt: __t.option(__t.timestamp()),
});
export type DirectMessage = __Infer<typeof DirectMessage>;

export const DirectParticipant = __t.object("DirectParticipant", {
  key: __t.string(),
  conversationId: __t.uuid(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  joinedAt: __t.timestamp(),
  leftAt: __t.option(__t.timestamp()),
  participantEpoch: __t.u64(),
});
export type DirectParticipant = __Infer<typeof DirectParticipant>;

export const DirectReadState = __t.object("DirectReadState", {
  key: __t.string(),
  conversationId: __t.uuid(),
  identity: __t.identity(),
  lastReadSequence: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type DirectReadState = __Infer<typeof DirectReadState>;

export const DirectReplyAncestry = __t.object("DirectReplyAncestry", {
  key: __t.string(),
  ancestorMessageId: __t.uuid(),
  descendantMessageId: __t.uuid(),
  conversationId: __t.uuid(),
  depth: __t.u32(),
});
export type DirectReplyAncestry = __Infer<typeof DirectReplyAncestry>;

export const DmPromotionConsent = __t.object("DmPromotionConsent", {
  key: __t.string(),
  proposalId: __t.uuid(),
  identity: __t.identity(),
  get decision() {
    return DmPromotionDecision;
  },
  proposalHash: __t.string(),
  decidedAt: __t.timestamp(),
});
export type DmPromotionConsent = __Infer<typeof DmPromotionConsent>;

// The tagged union or sum type for the algebraic type `DmPromotionDecision`.
export const DmPromotionDecision = __t.enum("DmPromotionDecision", {
  Approve: __t.unit(),
  Reject: __t.unit(),
});
export type DmPromotionDecision = __Infer<typeof DmPromotionDecision>;

export const DmPromotionProposal = __t.object("DmPromotionProposal", {
  id: __t.uuid(),
  conversationId: __t.uuid(),
  workspaceId: __t.uuid(),
  destinationSpaceId: __t.uuid(),
  proposerIdentity: __t.identity(),
  title: __t.string(),
  body: __t.string(),
  draftHash: __t.string(),
  sourceRevisionHash: __t.string(),
  proposalHash: __t.string(),
  participantEpochHash: __t.string(),
  get state() {
    return DmPromotionState;
  },
  revision: __t.u64(),
  expiresAt: __t.timestamp(),
  finalizedPostId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DmPromotionProposal = __Infer<typeof DmPromotionProposal>;

export const DmPromotionSource = __t.object("DmPromotionSource", {
  key: __t.string(),
  proposalId: __t.uuid(),
  messageId: __t.uuid(),
  messageRevision: __t.u64(),
  ordinal: __t.u32(),
});
export type DmPromotionSource = __Infer<typeof DmPromotionSource>;

// The tagged union or sum type for the algebraic type `DmPromotionState`.
export const DmPromotionState = __t.enum("DmPromotionState", {
  Pending: __t.unit(),
  Rejected: __t.unit(),
  Canceled: __t.unit(),
  Expired: __t.unit(),
  Finalized: __t.unit(),
});
export type DmPromotionState = __Infer<typeof DmPromotionState>;

export const EffectLedger = __t.object("EffectLedger", {
  effectKey: __t.string(),
  toolCallId: __t.uuid(),
  runId: __t.uuid(),
  normalizedArgsHash: __t.string(),
  ownerIdentity: __t.option(__t.identity()),
  ownerGeneration: __t.u64(),
  get state() {
    return EffectLedgerState;
  },
  providerReference: __t.string(),
  resultSummary: __t.string(),
  updatedAt: __t.timestamp(),
});
export type EffectLedger = __Infer<typeof EffectLedger>;

// The tagged union or sum type for the algebraic type `EffectLedgerState`.
export const EffectLedgerState = __t.enum("EffectLedgerState", {
  Pending: __t.unit(),
  Acquired: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  OutcomeUnknown: __t.unit(),
});
export type EffectLedgerState = __Infer<typeof EffectLedgerState>;

export const FileExtractionInput = __t.object("FileExtractionInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  extractedText: __t.string(),
});
export type FileExtractionInput = __Infer<typeof FileExtractionInput>;

export const FileProcessingPlanView = __t.object("FileProcessingPlanView", {
  jobId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  kind: __t.string(),
  sourceKey: __t.string(),
  cleanDestinationKey: __t.string(),
  cleanupPrefix: __t.string(),
  maxBytes: __t.u64(),
  maxExtractedCharacters: __t.u64(),
  allowedTypes: __t.array(__t.string()),
  get state() {
    return FileSecurityState;
  },
  leaseGeneration: __t.u64(),
});
export type FileProcessingPlanView = __Infer<typeof FileProcessingPlanView>;

export const FileRecord = __t.object("FileRecord", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  fileName: __t.string(),
  sourceKey: __t.string(),
  cleanKey: __t.string(),
  cleanupPrefix: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  detectedType: __t.string(),
  scanner: __t.string(),
  extractedText: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileRecord = __Infer<typeof FileRecord>;

export const FileScanOutcomeInput = __t.object("FileScanOutcomeInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  detectedType: __t.string(),
  clean: __t.bool(),
  cleanKey: __t.string(),
  scanner: __t.string(),
});
export type FileScanOutcomeInput = __Infer<typeof FileScanOutcomeInput>;

// The tagged union or sum type for the algebraic type `FileSecurityState`.
export const FileSecurityState = __t.enum("FileSecurityState", {
  UploadPending: __t.unit(),
  Uploaded: __t.unit(),
  Scanning: __t.unit(),
  Clean: __t.unit(),
  Rejected: __t.unit(),
  Extracted: __t.unit(),
  Deleted: __t.unit(),
});
export type FileSecurityState = __Infer<typeof FileSecurityState>;

export const FileUpload = __t.object("FileUpload", {
  id: __t.uuid(),
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  sourceKey: __t.string(),
  completed: __t.bool(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type FileUpload = __Infer<typeof FileUpload>;

export const FileUploadInput = __t.object("FileUploadInput", {
  spaceId: __t.uuid(),
  fileName: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  clientRequestId: __t.uuid(),
});
export type FileUploadInput = __Infer<typeof FileUploadInput>;

export const FileVersion = __t.object("FileVersion", {
  key: __t.string(),
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  contentVersion: __t.u64(),
  sourceKey: __t.string(),
  cleanKey: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  detectedType: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileVersion = __Infer<typeof FileVersion>;

export const HeartbeatPresenceInput = __t.object("HeartbeatPresenceInput", {
  workspaceId: __t.uuid(),
  sessionId: __t.uuid(),
  get deviceKind() {
    return PresenceDeviceKind;
  },
  deviceLabel: __t.string(),
  get status() {
    return PresenceStatus;
  },
  ttlSeconds: __t.u32(),
});
export type HeartbeatPresenceInput = __Infer<typeof HeartbeatPresenceInput>;

export const InstallAgentInput = __t.object("InstallAgentInput", {
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  secretRef: __t.string(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  maxAttempts: __t.u32(),
  maxAgeSeconds: __t.u32(),
  clientRequestId: __t.uuid(),
});
export type InstallAgentInput = __Infer<typeof InstallAgentInput>;

export const NamedThread = __t.object("NamedThread", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  rootPostId: __t.uuid(),
  title: __t.string(),
  archived: __t.bool(),
  revision: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NamedThread = __Infer<typeof NamedThread>;

export const Notification = __t.object("Notification", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  get kind() {
    return NotificationKind;
  },
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  summary: __t.string(),
  readAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const NotificationControl = __t.object("NotificationControl", {
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  spaceId: __t.option(__t.uuid()),
  get tier() {
    return NotificationTier;
  },
  get eventClass() {
    return NotificationKind;
  },
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  occurrenceCount: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  channel: __t.string(),
  get deliveryState() {
    return NotificationDeliveryState;
  },
  suppressionReason: __t.string(),
  windowStartedAt: __t.timestamp(),
  windowExpiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationControl = __Infer<typeof NotificationControl>;

// The tagged union or sum type for the algebraic type `NotificationDeliveryMode`.
export const NotificationDeliveryMode = __t.enum("NotificationDeliveryMode", {
  Immediate: __t.unit(),
  Digest: __t.unit(),
  Disabled: __t.unit(),
});
export type NotificationDeliveryMode = __Infer<typeof NotificationDeliveryMode>;

export const NotificationDeliveryPermit = __t.object("NotificationDeliveryPermit", {
  jobId: __t.uuid(),
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  serviceIdentity: __t.identity(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  resourceRevision: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  channel: __t.string(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type NotificationDeliveryPermit = __Infer<typeof NotificationDeliveryPermit>;

export const NotificationDeliveryPlanView = __t.object("NotificationDeliveryPlanView", {
  jobId: __t.uuid(),
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  channel: __t.string(),
  get deliveryState() {
    return NotificationDeliveryState;
  },
  suppressionReason: __t.string(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  permitExpiresAt: __t.option(__t.timestamp()),
});
export type NotificationDeliveryPlanView = __Infer<typeof NotificationDeliveryPlanView>;

// The tagged union or sum type for the algebraic type `NotificationDeliveryState`.
export const NotificationDeliveryState = __t.enum("NotificationDeliveryState", {
  Pending: __t.unit(),
  Suppressed: __t.unit(),
});
export type NotificationDeliveryState = __Infer<typeof NotificationDeliveryState>;

export const NotificationGroup = __t.object("NotificationGroup", {
  baseKey: __t.string(),
  groupKey: __t.string(),
  notificationId: __t.uuid(),
  groupRevision: __t.u64(),
  windowStartedAt: __t.timestamp(),
  windowExpiresAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationGroup = __Infer<typeof NotificationGroup>;

// The tagged union or sum type for the algebraic type `NotificationKind`.
export const NotificationKind = __t.enum("NotificationKind", {
  Mention: __t.unit(),
  Assignment: __t.unit(),
  Decision: __t.unit(),
  Agent: __t.unit(),
  System: __t.unit(),
});
export type NotificationKind = __Infer<typeof NotificationKind>;

export const NotificationPreference = __t.object("NotificationPreference", {
  key: __t.string(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get directMode() {
    return NotificationDeliveryMode;
  },
  get importantMode() {
    return NotificationDeliveryMode;
  },
  get ambientMode() {
    return NotificationDeliveryMode;
  },
  muteStartLocalMinute: __t.option(__t.u16()),
  muteEndLocalMinute: __t.option(__t.u16()),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationPreference = __Infer<typeof NotificationPreference>;

// The tagged union or sum type for the algebraic type `NotificationTier`.
export const NotificationTier = __t.enum("NotificationTier", {
  Direct: __t.unit(),
  Important: __t.unit(),
  Ambient: __t.unit(),
});
export type NotificationTier = __Infer<typeof NotificationTier>;

export const OutboxJob = __t.object("OutboxJob", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  effectKey: __t.string(),
  get state() {
    return OutboxState;
  },
  kind: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.option(__t.u64()),
  intentId: __t.option(__t.uuid()),
  recipientId: __t.option(__t.identity()),
  channel: __t.string(),
  authorizationEpoch: __t.option(__t.u64()),
  minimalMessage: __t.string(),
  payloadResourceId: __t.option(__t.uuid()),
  rebuildId: __t.option(__t.uuid()),
  generation: __t.option(__t.u64()),
  fileId: __t.option(__t.uuid()),
  version: __t.option(__t.u64()),
  runId: __t.option(__t.uuid()),
  expiresAt: __t.timestamp(),
  attempt: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  nextAttemptAt: __t.timestamp(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type OutboxJob = __Infer<typeof OutboxJob>;

export const OutboxJobEnvelopeView = __t.object("OutboxJobEnvelopeView", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  kind: __t.string(),
  effectKey: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.option(__t.u64()),
  intentId: __t.option(__t.uuid()),
  recipientId: __t.option(__t.identity()),
  channel: __t.string(),
  authorizationEpoch: __t.option(__t.u64()),
  minimalMessage: __t.string(),
  payloadResourceId: __t.option(__t.uuid()),
  rebuildId: __t.option(__t.uuid()),
  generation: __t.option(__t.u64()),
  fileId: __t.option(__t.uuid()),
  version: __t.option(__t.u64()),
  runId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  nextAttemptAt: __t.timestamp(),
  attempt: __t.u32(),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  lastError: __t.string(),
});
export type OutboxJobEnvelopeView = __Infer<typeof OutboxJobEnvelopeView>;

// The tagged union or sum type for the algebraic type `OutboxState`.
export const OutboxState = __t.enum("OutboxState", {
  Pending: __t.unit(),
  Leased: __t.unit(),
  Succeeded: __t.unit(),
  Retry: __t.unit(),
  OutcomeUnknown: __t.unit(),
  DeadLetter: __t.unit(),
});
export type OutboxState = __Infer<typeof OutboxState>;

export const PendingOperatorTransfer = __t.object("PendingOperatorTransfer", {
  singleton: __t.u8(),
  proposedSubject: __t.string(),
  authorityRevision: __t.u64(),
  proposedBy: __t.identity(),
  proposedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PendingOperatorTransfer = __Infer<typeof PendingOperatorTransfer>;

export const PlatformAuditLog = __t.object("PlatformAuditLog", {
  id: __t.uuid(),
  actorIdentity: __t.identity(),
  actorSubject: __t.string(),
  workspaceId: __t.option(__t.uuid()),
  action: __t.string(),
  resource: __t.string(),
  requestId: __t.uuid(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type PlatformAuditLog = __Infer<typeof PlatformAuditLog>;

export const PlatformAuthority = __t.object("PlatformAuthority", {
  singleton: __t.u8(),
  operatorSubject: __t.string(),
  revision: __t.u64(),
  updatedBy: __t.identity(),
  configuredAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PlatformAuthority = __Infer<typeof PlatformAuthority>;

export const PlatformCommandReceipt = __t.object("PlatformCommandReceipt", {
  key: __t.string(),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  inputHash: __t.string(),
  actorSubject: __t.string(),
  committedRevision: __t.u64(),
  committedAt: __t.timestamp(),
});
export type PlatformCommandReceipt = __Infer<typeof PlatformCommandReceipt>;

export const Poll = __t.object("Poll", {
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  allowsMultiple: __t.bool(),
  closed: __t.bool(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Poll = __Infer<typeof Poll>;

export const PollOption = __t.object("PollOption", {
  id: __t.uuid(),
  postId: __t.uuid(),
  label: __t.string(),
  position: __t.u32(),
});
export type PollOption = __Infer<typeof PollOption>;

export const PollVote = __t.object("PollVote", {
  key: __t.string(),
  postId: __t.uuid(),
  optionId: __t.uuid(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type PollVote = __Infer<typeof PollVote>;

export const Post = __t.object("Post", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  authorIdentity: __t.identity(),
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  get kind() {
    return PostKind;
  },
  get state() {
    return PostState;
  },
  locked: __t.bool(),
  title: __t.string(),
  body: __t.string(),
  revision: __t.u64(),
  activitySequence: __t.u64(),
  lastActivityAt: __t.timestamp(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Post = __Infer<typeof Post>;

export const PostActivity = __t.object("PostActivity", {
  key: __t.string(),
  postId: __t.uuid(),
  sequence: __t.u64(),
  actorIdentity: __t.identity(),
  kind: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostActivity = __Infer<typeof PostActivity>;

// The tagged union or sum type for the algebraic type `PostKind`.
export const PostKind = __t.enum("PostKind", {
  Discussion: __t.unit(),
  Question: __t.unit(),
  Announcement: __t.unit(),
  Decision: __t.unit(),
  Task: __t.unit(),
  Poll: __t.unit(),
  Incident: __t.unit(),
  MediaDrop: __t.unit(),
});
export type PostKind = __Infer<typeof PostKind>;

export const PostMention = __t.object("PostMention", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  createdAt: __t.timestamp(),
});
export type PostMention = __Infer<typeof PostMention>;

export const PostPin = __t.object("PostPin", {
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  pinnedBy: __t.identity(),
  pinnedAt: __t.timestamp(),
});
export type PostPin = __Infer<typeof PostPin>;

export const PostReaction = __t.object("PostReaction", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostReaction = __Infer<typeof PostReaction>;

// The tagged union or sum type for the algebraic type `PostState`.
export const PostState = __t.enum("PostState", {
  Active: __t.unit(),
  Resolved: __t.unit(),
  Archived: __t.unit(),
});
export type PostState = __Infer<typeof PostState>;

export const PostTag = __t.object("PostTag", {
  key: __t.string(),
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  tag: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostTag = __Infer<typeof PostTag>;

export const PostUserState = __t.object("PostUserState", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  following: __t.bool(),
  bookmarked: __t.bool(),
  lastReadSequence: __t.u64(),
  readAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PostUserState = __Infer<typeof PostUserState>;

// The tagged union or sum type for the algebraic type `PresenceDeviceKind`.
export const PresenceDeviceKind = __t.enum("PresenceDeviceKind", {
  Web: __t.unit(),
  Desktop: __t.unit(),
  Mobile: __t.unit(),
  Other: __t.unit(),
});
export type PresenceDeviceKind = __Infer<typeof PresenceDeviceKind>;

export const PresenceExpirySchedule = __t.object("PresenceExpirySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  presenceKey: __t.string(),
  expectedExpiresAt: __t.timestamp(),
});
export type PresenceExpirySchedule = __Infer<typeof PresenceExpirySchedule>;

export const PresenceSession = __t.object("PresenceSession", {
  key: __t.string(),
  scopeKey: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  sessionId: __t.uuid(),
  get deviceKind() {
    return PresenceDeviceKind;
  },
  deviceLabel: __t.string(),
  get status() {
    return PresenceStatus;
  },
  createdAt: __t.timestamp(),
  heartbeatAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PresenceSession = __Infer<typeof PresenceSession>;

// The tagged union or sum type for the algebraic type `PresenceStatus`.
export const PresenceStatus = __t.enum("PresenceStatus", {
  Online: __t.unit(),
  Away: __t.unit(),
  DoNotDisturb: __t.unit(),
});
export type PresenceStatus = __Infer<typeof PresenceStatus>;

export const ProposeDmPromotionInput = __t.object("ProposeDmPromotionInput", {
  conversationId: __t.uuid(),
  destinationSpaceId: __t.uuid(),
  title: __t.string(),
  body: __t.string(),
  sourceMessageIds: __t.array(__t.uuid()),
  expiresInSeconds: __t.u32(),
  clientRequestId: __t.uuid(),
});
export type ProposeDmPromotionInput = __Infer<typeof ProposeDmPromotionInput>;

export const ReplyAncestry = __t.object("ReplyAncestry", {
  key: __t.string(),
  ancestorId: __t.uuid(),
  descendantId: __t.uuid(),
  threadId: __t.uuid(),
  depth: __t.u32(),
});
export type ReplyAncestry = __Infer<typeof ReplyAncestry>;

export const SearchDocumentSnapshot = __t.object("SearchDocumentSnapshot", {
  effectKey: __t.string(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  tombstone: __t.bool(),
  allowedIdentities: __t.array(__t.identity()),
  createdAt: __t.timestamp(),
});
export type SearchDocumentSnapshot = __Infer<typeof SearchDocumentSnapshot>;

export const SearchWorkItem = __t.object("SearchWorkItem", {
  jobId: __t.uuid(),
  effectKey: __t.string(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  tombstone: __t.bool(),
  allowedIdentities: __t.array(__t.identity()),
  get state() {
    return OutboxState;
  },
  leaseGeneration: __t.u64(),
});
export type SearchWorkItem = __Infer<typeof SearchWorkItem>;

export const ServiceGrant = __t.object("ServiceGrant", {
  key: __t.string(),
  serviceIdentity: __t.identity(),
  workspaceId: __t.uuid(),
  kind: __t.string(),
  enabled: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ServiceGrant = __Infer<typeof ServiceGrant>;

export const ServicePrincipal = __t.object("ServicePrincipal", {
  identity: __t.identity(),
  name: __t.string(),
  enabled: __t.bool(),
  canRunAgents: __t.bool(),
  canProcessOutbox: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ServicePrincipal = __Infer<typeof ServicePrincipal>;

export const SetAgentToolPolicyInput = __t.object("SetAgentToolPolicyInput", {
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  expectedInstallationEpoch: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type SetAgentToolPolicyInput = __Infer<typeof SetAgentToolPolicyInput>;

export const SetNotificationPreferenceInput = __t.object("SetNotificationPreferenceInput", {
  workspaceId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get directMode() {
    return NotificationDeliveryMode;
  },
  get importantMode() {
    return NotificationDeliveryMode;
  },
  get ambientMode() {
    return NotificationDeliveryMode;
  },
  muteStartLocalMinute: __t.option(__t.u16()),
  muteEndLocalMinute: __t.option(__t.u16()),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type SetNotificationPreferenceInput = __Infer<typeof SetNotificationPreferenceInput>;

export const Space = __t.object("Space", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  get visibility() {
    return SpaceVisibility;
  },
  archived: __t.bool(),
  revision: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Space = __Infer<typeof Space>;

export const SpaceMember = __t.object("SpaceMember", {
  key: __t.string(),
  spaceId: __t.uuid(),
  identity: __t.identity(),
  active: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SpaceMember = __Infer<typeof SpaceMember>;

// The tagged union or sum type for the algebraic type `SpaceVisibility`.
export const SpaceVisibility = __t.enum("SpaceVisibility", {
  Workspace: __t.unit(),
  Private: __t.unit(),
});
export type SpaceVisibility = __Infer<typeof SpaceVisibility>;

export const TaskItem = __t.object("TaskItem", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  assigneeIdentity: __t.identity(),
  title: __t.string(),
  get status() {
    return TaskStatus;
  },
  createdBy: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type TaskItem = __Infer<typeof TaskItem>;

// The tagged union or sum type for the algebraic type `TaskStatus`.
export const TaskStatus = __t.enum("TaskStatus", {
  Todo: __t.unit(),
  InProgress: __t.unit(),
  Done: __t.unit(),
  Canceled: __t.unit(),
});
export type TaskStatus = __Infer<typeof TaskStatus>;

// The tagged union or sum type for the algebraic type `ToolCallState`.
export const ToolCallState = __t.enum("ToolCallState", {
  Proposed: __t.unit(),
  AwaitingApproval: __t.unit(),
  Approved: __t.unit(),
  Executing: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  OutcomeUnknown: __t.unit(),
  Canceled: __t.unit(),
});
export type ToolCallState = __Infer<typeof ToolCallState>;

// The tagged union or sum type for the algebraic type `ToolEffectClass`.
export const ToolEffectClass = __t.enum("ToolEffectClass", {
  Read: __t.unit(),
  External: __t.unit(),
  Destructive: __t.unit(),
});
export type ToolEffectClass = __Infer<typeof ToolEffectClass>;

export const TrustedTool = __t.object("TrustedTool", {
  key: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredAt: __t.timestamp(),
});
export type TrustedTool = __Infer<typeof TrustedTool>;

export const UpdatePostLifecycleInput = __t.object("UpdatePostLifecycleInput", {
  postId: __t.uuid(),
  get state() {
    return PostState;
  },
  locked: __t.bool(),
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type UpdatePostLifecycleInput = __Infer<typeof UpdatePostLifecycleInput>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.string(),
  disabled: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VisibleAgentInstallation = __t.object("VisibleAgentInstallation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  enabled: __t.bool(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  installedBy: __t.identity(),
});
export type VisibleAgentInstallation = __Infer<typeof VisibleAgentInstallation>;

export const VisibleAgentRun = __t.object("VisibleAgentRun", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  installationId: __t.uuid(),
  spaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  initiatedBy: __t.identity(),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  cancelRequested: __t.bool(),
  promptSummary: __t.string(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentRun = __Infer<typeof VisibleAgentRun>;

export const VisibleAgentScope = __t.object("VisibleAgentScope", {
  installationId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get capability() {
    return AgentCapability;
  },
  enabled: __t.bool(),
});
export type VisibleAgentScope = __Infer<typeof VisibleAgentScope>;

export const VisibleAgentToolCall = __t.object("VisibleAgentToolCall", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  requiresApproval: __t.bool(),
  get state() {
    return ToolCallState;
  },
  resultSummary: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentToolCall = __Infer<typeof VisibleAgentToolCall>;

export const VisibleAgentToolPolicy = __t.object("VisibleAgentToolPolicy", {
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  trustedToolRevision: __t.u64(),
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentToolPolicy = __Infer<typeof VisibleAgentToolPolicy>;

export const VisibleApproval = __t.object("VisibleApproval", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolCallId: __t.uuid(),
  get effectClass() {
    return ToolEffectClass;
  },
  get state() {
    return ApprovalState;
  },
  decidedBy: __t.option(__t.identity()),
  expiresAt: __t.timestamp(),
});
export type VisibleApproval = __Infer<typeof VisibleApproval>;

export const VisibleCommandReceipt = __t.object("VisibleCommandReceipt", {
  workspaceId: __t.option(__t.uuid()),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  resultType: __t.string(),
  resultId: __t.uuid(),
  committedAt: __t.timestamp(),
});
export type VisibleCommandReceipt = __Infer<typeof VisibleCommandReceipt>;

export const VisibleFile = __t.object("VisibleFile", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  fileName: __t.string(),
  declaredSizeBytes: __t.u64(),
  detectedType: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleFile = __Infer<typeof VisibleFile>;

export const VisiblePollOption = __t.object("VisiblePollOption", {
  id: __t.uuid(),
  postId: __t.uuid(),
  label: __t.string(),
  position: __t.u32(),
  voteCount: __t.u64(),
  viewerSelected: __t.bool(),
});
export type VisiblePollOption = __Infer<typeof VisiblePollOption>;

export const VisiblePostUserState = __t.object("VisiblePostUserState", {
  postId: __t.uuid(),
  following: __t.bool(),
  bookmarked: __t.bool(),
  unread: __t.bool(),
  lastReadSequence: __t.u64(),
  readAt: __t.option(__t.timestamp()),
});
export type VisiblePostUserState = __Infer<typeof VisiblePostUserState>;

export const VisiblePresence = __t.object("VisiblePresence", {
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get status() {
    return PresenceStatus;
  },
  expiresAt: __t.timestamp(),
});
export type VisiblePresence = __Infer<typeof VisiblePresence>;

export const VisibleUser = __t.object("VisibleUser", {
  identity: __t.identity(),
  displayName: __t.string(),
});
export type VisibleUser = __Infer<typeof VisibleUser>;

export const VisibleWorkspaceLifecycle = __t.object("VisibleWorkspaceLifecycle", {
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLifecycleState;
  },
  lifecycleEpoch: __t.u64(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  deletionExecuteAfter: __t.option(__t.timestamp()),
  revision: __t.u64(),
});
export type VisibleWorkspaceLifecycle = __Infer<typeof VisibleWorkspaceLifecycle>;

export const VisibleWorkspaceMember = __t.object("VisibleWorkspaceMember", {
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get role() {
    return WorkspaceRole;
  },
  active: __t.bool(),
});
export type VisibleWorkspaceMember = __Infer<typeof VisibleWorkspaceMember>;

export const Workspace = __t.object("Workspace", {
  id: __t.uuid(),
  name: __t.string(),
  ownerIdentity: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Workspace = __Infer<typeof Workspace>;

export const WorkspaceLifecycle = __t.object("WorkspaceLifecycle", {
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLifecycleState;
  },
  lifecycleEpoch: __t.u64(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  deletionRequestedBy: __t.option(__t.identity()),
  deletionRequestedAt: __t.option(__t.timestamp()),
  deletionExecuteAfter: __t.option(__t.timestamp()),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceLifecycle = __Infer<typeof WorkspaceLifecycle>;

export const WorkspaceLifecycleCommandInput = __t.object("WorkspaceLifecycleCommandInput", {
  workspaceId: __t.uuid(),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type WorkspaceLifecycleCommandInput = __Infer<typeof WorkspaceLifecycleCommandInput>;

export const WorkspaceLifecycleDrainSchedule = __t.object("WorkspaceLifecycleDrainSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  workspaceId: __t.uuid(),
  lifecycleEpoch: __t.u64(),
});
export type WorkspaceLifecycleDrainSchedule = __Infer<typeof WorkspaceLifecycleDrainSchedule>;

// The tagged union or sum type for the algebraic type `WorkspaceLifecycleState`.
export const WorkspaceLifecycleState = __t.enum("WorkspaceLifecycleState", {
  Active: __t.unit(),
  DeletionRequested: __t.unit(),
  DeletionFenced: __t.unit(),
});
export type WorkspaceLifecycleState = __Infer<typeof WorkspaceLifecycleState>;

export const WorkspaceMember = __t.object("WorkspaceMember", {
  key: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get role() {
    return WorkspaceRole;
  },
  active: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceMember = __Infer<typeof WorkspaceMember>;

// The tagged union or sum type for the algebraic type `WorkspaceRole`.
export const WorkspaceRole = __t.enum("WorkspaceRole", {
  Owner: __t.unit(),
  Admin: __t.unit(),
  Member: __t.unit(),
  Guest: __t.unit(),
});
export type WorkspaceRole = __Infer<typeof WorkspaceRole>;
