// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentApprovalBindingView = __t.object("AgentApprovalBindingView", {
  approvalId: __t.uuid(),
  nonceHash: __t.string(),
  runId: __t.uuid(),
  callId: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  argumentsHash: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  effectKey: __t.string(),
  expiresAt: __t.timestamp(),
  get state() {
    return ApprovalState;
  },
});
export type AgentApprovalBindingView = __Infer<typeof AgentApprovalBindingView>;

// The tagged union or sum type for the algebraic type `AgentCapability`.
export const AgentCapability = __t.enum("AgentCapability", {
  ReadSpace: __t.unit(),
  ReadHistory: __t.unit(),
  WriteContribution: __t.unit(),
  UseReadTool: __t.unit(),
  UseExternalTool: __t.unit(),
});
export type AgentCapability = __Infer<typeof AgentCapability>;

export const AgentContextCandidate = __t.object("AgentContextCandidate", {
  runId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentContextCandidate = __Infer<typeof AgentContextCandidate>;

export const AgentContextContributionInput = __t.object("AgentContextContributionInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  contributionId: __t.uuid(),
  expectedRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
});
export type AgentContextContributionInput = __Infer<typeof AgentContextContributionInput>;

export const AgentContextManifest = __t.object("AgentContextManifest", {
  id: __t.uuid(),
  runId: __t.uuid(),
  runResourceKey: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
  policyVersion: __t.u32(),
  createdAt: __t.timestamp(),
});
export type AgentContextManifest = __Infer<typeof AgentContextManifest>;

export const AgentContextPostInput = __t.object("AgentContextPostInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  postId: __t.uuid(),
  expectedRevision: __t.u64(),
  sourceHash: __t.string(),
  trustClass: __t.string(),
  redactionSummary: __t.string(),
});
export type AgentContextPostInput = __Infer<typeof AgentContextPostInput>;

export const AgentExecutionCheckpoint = __t.object("AgentExecutionCheckpoint", {
  key: __t.string(),
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  sequence: __t.u64(),
  get state() {
    return AgentRunState;
  },
  code: __t.string(),
  detailsJson: __t.string(),
  createdAtMillis: __t.u64(),
  recordedAt: __t.timestamp(),
});
export type AgentExecutionCheckpoint = __Infer<typeof AgentExecutionCheckpoint>;

export const AgentExecutionPlanView = __t.object("AgentExecutionPlanView", {
  runId: __t.uuid(),
  workspaceId: __t.uuid(),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  authorizationEpoch: __t.u64(),
  currentAuthorizationEpoch: __t.u64(),
  installationEnabled: __t.bool(),
  cancelRequested: __t.bool(),
  leaseGeneration: __t.u64(),
  leaseOwner: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  executionRequestId: __t.string(),
  maxContextBytes: __t.u64(),
  maxOutputTokens: __t.u64(),
  maxToolCalls: __t.u32(),
  maxCostMicros: __t.u64(),
  maxOutputBytes: __t.u64(),
  maxToolResultBytes: __t.u64(),
  maxTotalToolResultBytes: __t.u64(),
  maxProviderInputBytes: __t.u64(),
  maxTotalProviderInputBytes: __t.u64(),
});
export type AgentExecutionPlanView = __Infer<typeof AgentExecutionPlanView>;

export const AgentExecutionProgress = __t.object("AgentExecutionProgress", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  sequence: __t.u64(),
  outputTokens: __t.u64(),
  costMicros: __t.u64(),
  toolCalls: __t.u32(),
  toolResultsJson: __t.string(),
  providerInputBytes: __t.u64(),
  pendingStepJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentExecutionProgress = __Infer<typeof AgentExecutionProgress>;

export const AgentInstallation = __t.object("AgentInstallation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  secretRef: __t.string(),
  enabled: __t.bool(),
  authzEpoch: __t.u64(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  maxAttempts: __t.u32(),
  maxAgeSeconds: __t.u32(),
  installedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentInstallation = __Infer<typeof AgentInstallation>;

export const AgentProviderDispatch = __t.object("AgentProviderDispatch", {
  key: __t.string(),
  runId: __t.uuid(),
  providerSequence: __t.u64(),
  leaseGeneration: __t.u64(),
  authorizationEpoch: __t.u64(),
  requestId: __t.string(),
  inputFingerprint: __t.string(),
  canonicalInput: __t.string(),
  inputBytes: __t.u64(),
  contextBindingHash: __t.string(),
  contextJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentProviderDispatch = __Infer<typeof AgentProviderDispatch>;

export const AgentRun = __t.object("AgentRun", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  installationId: __t.uuid(),
  spaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  initiatedBy: __t.identity(),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  installationEpoch: __t.u64(),
  membershipEpoch: __t.u64(),
  attempt: __t.u32(),
  cancelRequested: __t.bool(),
  leaseOwner: __t.option(__t.identity()),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  executionRequestId: __t.string(),
  expiresAt: __t.timestamp(),
  nextEventSequence: __t.u64(),
  promptSummary: __t.string(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
  finalContributionId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentRun = __Infer<typeof AgentRun>;

export const AgentRunEvent = __t.object("AgentRunEvent", {
  id: __t.uuid(),
  runId: __t.uuid(),
  sequence: __t.u64(),
  runSequenceKey: __t.string(),
  kind: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentRunEvent = __Infer<typeof AgentRunEvent>;

// The tagged union or sum type for the algebraic type `AgentRunState`.
export const AgentRunState = __t.enum("AgentRunState", {
  Queued: __t.unit(),
  Authorizing: __t.unit(),
  CollectingContext: __t.unit(),
  Running: __t.unit(),
  AwaitingApproval: __t.unit(),
  ExecutingTool: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  Canceled: __t.unit(),
  Expired: __t.unit(),
  Revoked: __t.unit(),
});
export type AgentRunState = __Infer<typeof AgentRunState>;

export const AgentScope = __t.object("AgentScope", {
  key: __t.string(),
  installationId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get capability() {
    return AgentCapability;
  },
  enabled: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentScope = __Infer<typeof AgentScope>;

export const AgentToolCall = __t.object("AgentToolCall", {
  id: __t.uuid(),
  runId: __t.uuid(),
  providerCallKey: __t.string(),
  providerCallId: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  policyKey: __t.string(),
  policyRevision: __t.u64(),
  get effectClass() {
    return ToolEffectClass;
  },
  normalizedArgsHash: __t.string(),
  effectKey: __t.string(),
  requiresApproval: __t.bool(),
  get state() {
    return ToolCallState;
  },
  resultSummary: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentToolCall = __Infer<typeof AgentToolCall>;

export const AgentToolCallInput = __t.object("AgentToolCallInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  expectedVersion: __t.u64(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  normalizedArgsHash: __t.string(),
  approvalNonceHash: __t.string(),
  clientRequestId: __t.uuid(),
});
export type AgentToolCallInput = __Infer<typeof AgentToolCallInput>;

export const AgentToolPolicy = __t.object("AgentToolPolicy", {
  key: __t.string(),
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  trustedToolRevision: __t.u64(),
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type AgentToolPolicy = __Infer<typeof AgentToolPolicy>;

export const ApprovalRequest = __t.object("ApprovalRequest", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolCallId: __t.uuid(),
  normalizedArgsHash: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  nonceHash: __t.string(),
  get state() {
    return ApprovalState;
  },
  requestedByService: __t.identity(),
  decidedBy: __t.option(__t.identity()),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  decidedAt: __t.option(__t.timestamp()),
});
export type ApprovalRequest = __Infer<typeof ApprovalRequest>;

// The tagged union or sum type for the algebraic type `ApprovalState`.
export const ApprovalState = __t.enum("ApprovalState", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Rejected: __t.unit(),
  Expired: __t.unit(),
  Consumed: __t.unit(),
});
export type ApprovalState = __Infer<typeof ApprovalState>;

export const AuditLog = __t.object("AuditLog", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  actorIdentity: __t.identity(),
  effectivePrincipal: __t.string(),
  action: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  requestId: __t.uuid(),
  policyVersion: __t.u32(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditLog = __Infer<typeof AuditLog>;

export const AuthPolicy = __t.object("AuthPolicy", {
  singleton: __t.u8(),
  issuer: __t.string(),
  audience: __t.string(),
  configuredBy: __t.identity(),
  configuredAt: __t.timestamp(),
});
export type AuthPolicy = __Infer<typeof AuthPolicy>;

export const AuthorizeNotificationDigestInput = __t.object("AuthorizeNotificationDigestInput", {
  claimId: __t.uuid(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  permitSeconds: __t.u32(),
});
export type AuthorizeNotificationDigestInput = __Infer<typeof AuthorizeNotificationDigestInput>;

export const BootstrapAuthority = __t.object("BootstrapAuthority", {
  singleton: __t.u8(),
  issuer: __t.string(),
  audience: __t.string(),
  ownerSubject: __t.string(),
  consumed: __t.bool(),
  configuredAt: __t.timestamp(),
});
export type BootstrapAuthority = __Infer<typeof BootstrapAuthority>;

export const ClaimAgentExecutionInput = __t.object("ClaimAgentExecutionInput", {
  runId: __t.uuid(),
  workspaceId: __t.uuid(),
  authorityJobId: __t.uuid(),
  executionRequestId: __t.string(),
  expectedVersion: __t.u64(),
  leaseSeconds: __t.u32(),
});
export type ClaimAgentExecutionInput = __Infer<typeof ClaimAgentExecutionInput>;

export const ClaimFileDeletionInput = __t.object("ClaimFileDeletionInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  key: __t.string(),
  objectVersionTag: __t.string(),
});
export type ClaimFileDeletionInput = __Infer<typeof ClaimFileDeletionInput>;

export const ClaimNotificationDigestsInput = __t.object("ClaimNotificationDigestsInput", {
  get occurrences() {
    return __t.array(NotificationDigestOccurrenceInput);
  },
  workerSlotId: __t.string(),
  leaseSeconds: __t.u32(),
});
export type ClaimNotificationDigestsInput = __Infer<typeof ClaimNotificationDigestsInput>;

export const CommandReceipt = __t.object("CommandReceipt", {
  key: __t.string(),
  actorIdentity: __t.identity(),
  workspaceId: __t.option(__t.uuid()),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  inputHash: __t.string(),
  resultType: __t.string(),
  resultId: __t.uuid(),
  committedAt: __t.timestamp(),
});
export type CommandReceipt = __Infer<typeof CommandReceipt>;

export const CommitAgentFinalInput = __t.object("CommitAgentFinalInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  authorizationEpoch: __t.u64(),
  text: __t.string(),
  progressSequence: __t.u64(),
  outputTokens: __t.u64(),
  costMicros: __t.u64(),
  toolCalls: __t.u32(),
  toolResultsJson: __t.string(),
  providerInputBytes: __t.u64(),
});
export type CommitAgentFinalInput = __Infer<typeof CommitAgentFinalInput>;

export const CompleteAgentRunInput = __t.object("CompleteAgentRunInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  expectedVersion: __t.u64(),
  succeeded: __t.bool(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
});
export type CompleteAgentRunInput = __Infer<typeof CompleteAgentRunInput>;

export const CompleteFileUploadInput = __t.object("CompleteFileUploadInput", {
  uploadId: __t.uuid(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  observedSizeBytes: __t.u64(),
  observedType: __t.string(),
  objectVersion: __t.string(),
  checksumSha256: __t.string(),
  clientRequestId: __t.uuid(),
});
export type CompleteFileUploadInput = __Infer<typeof CompleteFileUploadInput>;

export const CompleteWorkspaceExportCleanupInput = __t.object("CompleteWorkspaceExportCleanupInput", {
  exportId: __t.uuid(),
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  workerSlotId: __t.string(),
  get outcome() {
    return WorkspaceExportCleanupOutcome;
  },
  error: __t.string(),
  retryAfterSeconds: __t.u32(),
});
export type CompleteWorkspaceExportCleanupInput = __Infer<typeof CompleteWorkspaceExportCleanupInput>;

export const CompleteWorkspaceExportInput = __t.object("CompleteWorkspaceExportInput", {
  exportId: __t.uuid(),
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  workerSlotId: __t.string(),
  get outcome() {
    return WorkspaceExportCompletionOutcome;
  },
  artifactKey: __t.string(),
  contentHash: __t.string(),
  artifactVersion: __t.string(),
  sizeBytes: __t.u64(),
  error: __t.string(),
  retryAfterSeconds: __t.u32(),
});
export type CompleteWorkspaceExportInput = __Infer<typeof CompleteWorkspaceExportInput>;

export const ConfigurePollInput = __t.object("ConfigurePollInput", {
  postId: __t.uuid(),
  options: __t.array(__t.string()),
  allowsMultiple: __t.bool(),
  expectedPostRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type ConfigurePollInput = __Infer<typeof ConfigurePollInput>;

export const ConfigureWorkspaceLifecycleInput = __t.object("ConfigureWorkspaceLifecycleInput", {
  workspaceId: __t.uuid(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type ConfigureWorkspaceLifecycleInput = __Infer<typeof ConfigureWorkspaceLifecycleInput>;

export const ConsumeAgentApprovalInput = __t.object("ConsumeAgentApprovalInput", {
  runId: __t.uuid(),
  callId: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  normalizedArgsHash: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  nonceHash: __t.string(),
  effectKey: __t.string(),
});
export type ConsumeAgentApprovalInput = __Infer<typeof ConsumeAgentApprovalInput>;

export const Contribution = __t.object("Contribution", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.uuid(),
  authorIdentity: __t.identity(),
  agentInstallationId: __t.option(__t.uuid()),
  agentRunId: __t.option(__t.uuid()),
  parentContributionId: __t.option(__t.uuid()),
  get kind() {
    return ContributionKind;
  },
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Contribution = __Infer<typeof Contribution>;

// The tagged union or sum type for the algebraic type `ContributionKind`.
export const ContributionKind = __t.enum("ContributionKind", {
  Message: __t.unit(),
  Update: __t.unit(),
  Summary: __t.unit(),
  AgentOutput: __t.unit(),
});
export type ContributionKind = __Infer<typeof ContributionKind>;

export const CreateDirectConversationInput = __t.object("CreateDirectConversationInput", {
  workspaceId: __t.uuid(),
  participants: __t.array(__t.identity()),
  clientRequestId: __t.uuid(),
});
export type CreateDirectConversationInput = __Infer<typeof CreateDirectConversationInput>;

export const CreateTypedPostInput = __t.object("CreateTypedPostInput", {
  spaceId: __t.uuid(),
  title: __t.string(),
  body: __t.string(),
  get kind() {
    return PostKind;
  },
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  tags: __t.array(__t.string()),
  mentions: __t.array(__t.identity()),
  clientRequestId: __t.uuid(),
});
export type CreateTypedPostInput = __Infer<typeof CreateTypedPostInput>;

export const CurrentPresence = __t.object("CurrentPresence", {
  key: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get status() {
    return PresenceStatus;
  },
  expiresAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CurrentPresence = __Infer<typeof CurrentPresence>;

export const DecisionRecord = __t.object("DecisionRecord", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.uuid(),
  title: __t.string(),
  rationale: __t.string(),
  get status() {
    return DecisionStatus;
  },
  supersedesDecisionId: __t.option(__t.uuid()),
  createdBy: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DecisionRecord = __Infer<typeof DecisionRecord>;

// The tagged union or sum type for the algebraic type `DecisionStatus`.
export const DecisionStatus = __t.enum("DecisionStatus", {
  Proposed: __t.unit(),
  Accepted: __t.unit(),
  Rejected: __t.unit(),
  Superseded: __t.unit(),
});
export type DecisionStatus = __Infer<typeof DecisionStatus>;

export const DirectConversation = __t.object("DirectConversation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  createdBy: __t.identity(),
  nextSequence: __t.u64(),
  revision: __t.u64(),
  deactivatedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DirectConversation = __Infer<typeof DirectConversation>;

export const DirectMessage = __t.object("DirectMessage", {
  id: __t.uuid(),
  sequenceKey: __t.string(),
  conversationId: __t.uuid(),
  authorIdentity: __t.identity(),
  workspaceId: __t.uuid(),
  sequence: __t.u64(),
  parentMessageId: __t.option(__t.uuid()),
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
  deletedAt: __t.option(__t.timestamp()),
});
export type DirectMessage = __Infer<typeof DirectMessage>;

export const DirectParticipant = __t.object("DirectParticipant", {
  key: __t.string(),
  conversationId: __t.uuid(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  joinedAt: __t.timestamp(),
  leftAt: __t.option(__t.timestamp()),
  participantEpoch: __t.u64(),
});
export type DirectParticipant = __Infer<typeof DirectParticipant>;

export const DirectReadState = __t.object("DirectReadState", {
  key: __t.string(),
  conversationId: __t.uuid(),
  identity: __t.identity(),
  lastReadSequence: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type DirectReadState = __Infer<typeof DirectReadState>;

export const DirectReplyAncestry = __t.object("DirectReplyAncestry", {
  key: __t.string(),
  ancestorMessageId: __t.uuid(),
  descendantMessageId: __t.uuid(),
  conversationId: __t.uuid(),
  depth: __t.u32(),
});
export type DirectReplyAncestry = __Infer<typeof DirectReplyAncestry>;

export const DmPromotionConsent = __t.object("DmPromotionConsent", {
  key: __t.string(),
  proposalId: __t.uuid(),
  identity: __t.identity(),
  get decision() {
    return DmPromotionDecision;
  },
  proposalHash: __t.string(),
  decidedAt: __t.timestamp(),
});
export type DmPromotionConsent = __Infer<typeof DmPromotionConsent>;

// The tagged union or sum type for the algebraic type `DmPromotionDecision`.
export const DmPromotionDecision = __t.enum("DmPromotionDecision", {
  Approve: __t.unit(),
  Reject: __t.unit(),
});
export type DmPromotionDecision = __Infer<typeof DmPromotionDecision>;

export const DmPromotionProposal = __t.object("DmPromotionProposal", {
  id: __t.uuid(),
  conversationId: __t.uuid(),
  workspaceId: __t.uuid(),
  destinationSpaceId: __t.uuid(),
  proposerIdentity: __t.identity(),
  title: __t.string(),
  body: __t.string(),
  draftHash: __t.string(),
  sourceRevisionHash: __t.string(),
  proposalHash: __t.string(),
  participantEpochHash: __t.string(),
  get state() {
    return DmPromotionState;
  },
  revision: __t.u64(),
  expiresAt: __t.timestamp(),
  finalizedPostId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type DmPromotionProposal = __Infer<typeof DmPromotionProposal>;

export const DmPromotionSource = __t.object("DmPromotionSource", {
  key: __t.string(),
  proposalId: __t.uuid(),
  messageId: __t.uuid(),
  messageRevision: __t.u64(),
  ordinal: __t.u32(),
});
export type DmPromotionSource = __Infer<typeof DmPromotionSource>;

// The tagged union or sum type for the algebraic type `DmPromotionState`.
export const DmPromotionState = __t.enum("DmPromotionState", {
  Pending: __t.unit(),
  Rejected: __t.unit(),
  Canceled: __t.unit(),
  Expired: __t.unit(),
  Finalized: __t.unit(),
});
export type DmPromotionState = __Infer<typeof DmPromotionState>;

export const EffectLedger = __t.object("EffectLedger", {
  effectKey: __t.string(),
  toolCallId: __t.uuid(),
  runId: __t.uuid(),
  normalizedArgsHash: __t.string(),
  ownerIdentity: __t.option(__t.identity()),
  ownerGeneration: __t.u64(),
  get state() {
    return EffectLedgerState;
  },
  providerReference: __t.string(),
  resultSummary: __t.string(),
  updatedAt: __t.timestamp(),
});
export type EffectLedger = __Infer<typeof EffectLedger>;

// The tagged union or sum type for the algebraic type `EffectLedgerState`.
export const EffectLedgerState = __t.enum("EffectLedgerState", {
  Pending: __t.unit(),
  Acquired: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  OutcomeUnknown: __t.unit(),
});
export type EffectLedgerState = __Infer<typeof EffectLedgerState>;

export const FileDeletionClaim = __t.object("FileDeletionClaim", {
  claimId: __t.uuid(),
  fileKey: __t.string(),
  workspaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  jobId: __t.uuid(),
  serviceIdentity: __t.identity(),
  leaseGeneration: __t.u64(),
  generation: __t.u64(),
  key: __t.string(),
  objectVersionTag: __t.string(),
  get state() {
    return FileDeletionClaimState;
  },
  code: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileDeletionClaim = __Infer<typeof FileDeletionClaim>;

export const FileDeletionClaimInput = __t.object("FileDeletionClaimInput", {
  claimId: __t.uuid(),
  generation: __t.u64(),
  workspaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  key: __t.string(),
  objectVersionTag: __t.string(),
});
export type FileDeletionClaimInput = __Infer<typeof FileDeletionClaimInput>;

// The tagged union or sum type for the algebraic type `FileDeletionClaimState`.
export const FileDeletionClaimState = __t.enum("FileDeletionClaimState", {
  Claimed: __t.unit(),
  Finalized: __t.unit(),
  Released: __t.unit(),
});
export type FileDeletionClaimState = __Infer<typeof FileDeletionClaimState>;

export const FileDeletionClaimView = __t.object("FileDeletionClaimView", {
  claimId: __t.uuid(),
  generation: __t.u64(),
  workspaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  key: __t.string(),
  objectVersionTag: __t.string(),
});
export type FileDeletionClaimView = __Infer<typeof FileDeletionClaimView>;

export const FileExtractionInput = __t.object("FileExtractionInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  extractedText: __t.string(),
});
export type FileExtractionInput = __Infer<typeof FileExtractionInput>;

export const FileOrphanDiscrepancy = __t.object("FileOrphanDiscrepancy", {
  fileKey: __t.string(),
  workspaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  key: __t.string(),
  occurrenceCount: __t.u32(),
  resolved: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileOrphanDiscrepancy = __Infer<typeof FileOrphanDiscrepancy>;

export const FileProcessingOutcomeView = __t.object("FileProcessingOutcomeView", {
  jobId: __t.uuid(),
  workspaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  kind: __t.string(),
  outcome: __t.string(),
});
export type FileProcessingOutcomeView = __Infer<typeof FileProcessingOutcomeView>;

export const FileProcessingPlanView = __t.object("FileProcessingPlanView", {
  jobId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  fileId: __t.uuid(),
  fileRevision: __t.u64(),
  kind: __t.string(),
  sourceKey: __t.string(),
  sourceObjectVersion: __t.string(),
  sourceChecksumSha256: __t.string(),
  cleanDestinationKey: __t.string(),
  cleanupPrefix: __t.string(),
  maxBytes: __t.u64(),
  maxExtractedCharacters: __t.u64(),
  allowedTypes: __t.array(__t.string()),
  get state() {
    return FileSecurityState;
  },
  leaseGeneration: __t.u64(),
});
export type FileProcessingPlanView = __Infer<typeof FileProcessingPlanView>;

export const FileRecord = __t.object("FileRecord", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  fileName: __t.string(),
  declaredType: __t.string(),
  sourceKey: __t.string(),
  sourceObjectVersion: __t.string(),
  sourceChecksumSha256: __t.string(),
  cleanKey: __t.string(),
  cleanObjectVersion: __t.string(),
  cleanChecksumSha256: __t.string(),
  cleanupPrefix: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  detectedType: __t.string(),
  scanner: __t.string(),
  extractedText: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileRecord = __Infer<typeof FileRecord>;

export const FileScanOutcomeInput = __t.object("FileScanOutcomeInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  detectedType: __t.string(),
  clean: __t.bool(),
  cleanKey: __t.string(),
  scanner: __t.string(),
});
export type FileScanOutcomeInput = __Infer<typeof FileScanOutcomeInput>;

// The tagged union or sum type for the algebraic type `FileSecurityState`.
export const FileSecurityState = __t.enum("FileSecurityState", {
  UploadPending: __t.unit(),
  Uploaded: __t.unit(),
  Scanning: __t.unit(),
  Clean: __t.unit(),
  Rejected: __t.unit(),
  Extracted: __t.unit(),
  Deleted: __t.unit(),
});
export type FileSecurityState = __Infer<typeof FileSecurityState>;

export const FileUpload = __t.object("FileUpload", {
  id: __t.uuid(),
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  sourceKey: __t.string(),
  completed: __t.bool(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type FileUpload = __Infer<typeof FileUpload>;

export const FileUploadInput = __t.object("FileUploadInput", {
  reservationId: __t.uuid(),
  spaceId: __t.uuid(),
  fileName: __t.string(),
  declaredType: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  ttlSeconds: __t.u32(),
  clientRequestId: __t.uuid(),
});
export type FileUploadInput = __Infer<typeof FileUploadInput>;

export const FileVersion = __t.object("FileVersion", {
  key: __t.string(),
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  contentVersion: __t.u64(),
  sourceKey: __t.string(),
  declaredType: __t.string(),
  sourceObjectVersion: __t.string(),
  sourceChecksumSha256: __t.string(),
  cleanKey: __t.string(),
  cleanObjectVersion: __t.string(),
  cleanChecksumSha256: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksum: __t.string(),
  detectedType: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FileVersion = __Infer<typeof FileVersion>;

export const GatewayFileDescriptorView = __t.object("GatewayFileDescriptorView", {
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  fileName: __t.string(),
  objectKey: __t.string(),
  objectVersion: __t.string(),
  checksumSha256: __t.string(),
  detectedType: __t.string(),
  sizeBytes: __t.u64(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
});
export type GatewayFileDescriptorView = __Infer<typeof GatewayFileDescriptorView>;

export const GatewayPendingUploadView = __t.object("GatewayPendingUploadView", {
  uploadId: __t.uuid(),
  fileId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  uploaderIdentity: __t.identity(),
  sourceKey: __t.string(),
  fileName: __t.string(),
  declaredType: __t.string(),
  declaredSizeBytes: __t.u64(),
  checksumSha256: __t.string(),
  expiresAt: __t.timestamp(),
  completed: __t.bool(),
  get fileState() {
    return FileSecurityState;
  },
  fileRevision: __t.u64(),
});
export type GatewayPendingUploadView = __Infer<typeof GatewayPendingUploadView>;

export const GatewayPrincipalView = __t.object("GatewayPrincipalView", {
  identity: __t.identity(),
  authzEpoch: __t.u64(),
  disabled: __t.bool(),
});
export type GatewayPrincipalView = __Infer<typeof GatewayPrincipalView>;

export const GatewaySpaceGrantView = __t.object("GatewaySpaceGrantView", {
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  membershipEpoch: __t.u64(),
  canRead: __t.bool(),
  canWrite: __t.bool(),
  canRunAgents: __t.bool(),
});
export type GatewaySpaceGrantView = __Infer<typeof GatewaySpaceGrantView>;

export const GatewayWorkspaceGrantView = __t.object("GatewayWorkspaceGrantView", {
  workspaceId: __t.uuid(),
  get role() {
    return WorkspaceRole;
  },
  membershipEpoch: __t.u64(),
  userAuthzEpoch: __t.u64(),
  lifecycleEpoch: __t.u64(),
  canRead: __t.bool(),
  canWrite: __t.bool(),
  canManageMembers: __t.bool(),
  canManageWorkspace: __t.bool(),
  canManageAgents: __t.bool(),
  canRunAgents: __t.bool(),
});
export type GatewayWorkspaceGrantView = __Infer<typeof GatewayWorkspaceGrantView>;

export const HeartbeatPresenceInput = __t.object("HeartbeatPresenceInput", {
  workspaceId: __t.uuid(),
  sessionId: __t.uuid(),
  get deviceKind() {
    return PresenceDeviceKind;
  },
  deviceLabel: __t.string(),
  get status() {
    return PresenceStatus;
  },
  ttlSeconds: __t.u32(),
});
export type HeartbeatPresenceInput = __Infer<typeof HeartbeatPresenceInput>;

export const InstallAgentInput = __t.object("InstallAgentInput", {
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  secretRef: __t.string(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  maxAttempts: __t.u32(),
  maxAgeSeconds: __t.u32(),
  clientRequestId: __t.uuid(),
});
export type InstallAgentInput = __Infer<typeof InstallAgentInput>;

export const NamedThread = __t.object("NamedThread", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  rootPostId: __t.uuid(),
  title: __t.string(),
  archived: __t.bool(),
  revision: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NamedThread = __Infer<typeof NamedThread>;

export const Notification = __t.object("Notification", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  get kind() {
    return NotificationKind;
  },
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  summary: __t.string(),
  readAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const NotificationControl = __t.object("NotificationControl", {
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  spaceId: __t.option(__t.uuid()),
  get tier() {
    return NotificationTier;
  },
  get eventClass() {
    return NotificationKind;
  },
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  occurrenceCount: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  channel: __t.string(),
  get deliveryState() {
    return NotificationDeliveryState;
  },
  suppressionReason: __t.string(),
  windowStartedAt: __t.timestamp(),
  windowExpiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationControl = __Infer<typeof NotificationControl>;

// The tagged union or sum type for the algebraic type `NotificationDeliveryMode`.
export const NotificationDeliveryMode = __t.enum("NotificationDeliveryMode", {
  Immediate: __t.unit(),
  Digest: __t.unit(),
  Disabled: __t.unit(),
});
export type NotificationDeliveryMode = __Infer<typeof NotificationDeliveryMode>;

export const NotificationDeliveryPermit = __t.object("NotificationDeliveryPermit", {
  jobId: __t.uuid(),
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  serviceIdentity: __t.identity(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  resourceRevision: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  channel: __t.string(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type NotificationDeliveryPermit = __Infer<typeof NotificationDeliveryPermit>;

export const NotificationDeliveryPlanView = __t.object("NotificationDeliveryPlanView", {
  jobId: __t.uuid(),
  notificationId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  channel: __t.string(),
  get deliveryState() {
    return NotificationDeliveryState;
  },
  suppressionReason: __t.string(),
  groupKey: __t.string(),
  groupRevision: __t.u64(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  membershipEpoch: __t.u64(),
  preferenceRevision: __t.u64(),
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  permitExpiresAt: __t.option(__t.timestamp()),
});
export type NotificationDeliveryPlanView = __Infer<typeof NotificationDeliveryPlanView>;

// The tagged union or sum type for the algebraic type `NotificationDeliveryState`.
export const NotificationDeliveryState = __t.enum("NotificationDeliveryState", {
  Pending: __t.unit(),
  Suppressed: __t.unit(),
});
export type NotificationDeliveryState = __Infer<typeof NotificationDeliveryState>;

export const NotificationDigestClaim = __t.object("NotificationDigestClaim", {
  claimId: __t.uuid(),
  scheduleId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  channel: __t.string(),
  localDate: __t.string(),
  scheduledFor: __t.timestamp(),
  preferenceRevision: __t.u64(),
  digestRevision: __t.u64(),
  authorizationEpoch: __t.u64(),
  overflowCount: __t.u64(),
  get state() {
    return NotificationDigestClaimState;
  },
  serviceIdentity: __t.identity(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  leaseUntil: __t.timestamp(),
  attemptCount: __t.u32(),
  nextAttemptAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationDigestClaim = __Infer<typeof NotificationDigestClaim>;

// The tagged union or sum type for the algebraic type `NotificationDigestClaimState`.
export const NotificationDigestClaimState = __t.enum("NotificationDigestClaimState", {
  Claimed: __t.unit(),
  Retry: __t.unit(),
  OutcomeUnknown: __t.unit(),
});
export type NotificationDigestClaimState = __Infer<typeof NotificationDigestClaimState>;

// The tagged union or sum type for the algebraic type `NotificationDigestCompletionOutcome`.
export const NotificationDigestCompletionOutcome = __t.enum("NotificationDigestCompletionOutcome", {
  Succeeded: __t.unit(),
  Suppressed: __t.unit(),
  TransientFailure: __t.unit(),
  PermanentFailure: __t.unit(),
  OutcomeUnknown: __t.unit(),
  ReconciliationUnknown: __t.unit(),
});
export type NotificationDigestCompletionOutcome = __Infer<typeof NotificationDigestCompletionOutcome>;

export const NotificationDigestItem = __t.object("NotificationDigestItem", {
  notificationId: __t.uuid(),
  scheduleId: __t.uuid(),
  digestRevision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationDigestItem = __Infer<typeof NotificationDigestItem>;

export const NotificationDigestOccurrenceInput = __t.object("NotificationDigestOccurrenceInput", {
  scheduleId: __t.uuid(),
  localDate: __t.string(),
  scheduledFor: __t.timestamp(),
  expectedPreferenceRevision: __t.u64(),
  expectedDigestRevision: __t.u64(),
});
export type NotificationDigestOccurrenceInput = __Infer<typeof NotificationDigestOccurrenceInput>;

export const NotificationDigestOutcome = __t.object("NotificationDigestOutcome", {
  occurrenceKey: __t.string(),
  scheduleId: __t.uuid(),
  workspaceId: __t.uuid(),
  localDate: __t.string(),
  digestRevision: __t.u64(),
  get outcome() {
    return NotificationDigestTerminalOutcome;
  },
  providerReference: __t.string(),
  code: __t.string(),
  completedAt: __t.timestamp(),
});
export type NotificationDigestOutcome = __Infer<typeof NotificationDigestOutcome>;

export const NotificationDigestPermit = __t.object("NotificationDigestPermit", {
  claimId: __t.uuid(),
  workspaceId: __t.uuid(),
  scheduleId: __t.uuid(),
  serviceIdentity: __t.identity(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  preferenceRevision: __t.u64(),
  digestRevision: __t.u64(),
  authorizationEpoch: __t.u64(),
  expiresAt: __t.timestamp(),
  createdAt: __t.timestamp(),
});
export type NotificationDigestPermit = __Infer<typeof NotificationDigestPermit>;

export const NotificationDigestPlanView = __t.object("NotificationDigestPlanView", {
  claimId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  channel: __t.string(),
  scheduleId: __t.uuid(),
  localDate: __t.string(),
  scheduledFor: __t.timestamp(),
  preferenceRevision: __t.u64(),
  digestRevision: __t.u64(),
  authorizationEpoch: __t.u64(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  reconcileFirst: __t.bool(),
  decision: __t.string(),
  suppressionCode: __t.string(),
  body: __t.string(),
  itemCount: __t.u16(),
  permitExpiresAt: __t.option(__t.timestamp()),
});
export type NotificationDigestPlanView = __Infer<typeof NotificationDigestPlanView>;

export const NotificationDigestSchedule = __t.object("NotificationDigestSchedule", {
  id: __t.uuid(),
  key: __t.string(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  preferenceKey: __t.string(),
  channel: __t.string(),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  preferenceRevision: __t.u64(),
  digestRevision: __t.u64(),
  overflowCount: __t.u64(),
  overflowRevision: __t.u64(),
  lastOccurrenceLocalDate: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationDigestSchedule = __Infer<typeof NotificationDigestSchedule>;

export const NotificationDigestScheduleView = __t.object("NotificationDigestScheduleView", {
  scheduleId: __t.uuid(),
  workspaceId: __t.uuid(),
  recipientIdentity: __t.identity(),
  channel: __t.string(),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  preferenceRevision: __t.u64(),
  digestRevision: __t.u64(),
  lastOccurrenceLocalDate: __t.string(),
  activeClaimLocalDate: __t.string(),
  activeClaimScheduledFor: __t.option(__t.timestamp()),
  get activeClaimState() {
    return __t.option(NotificationDigestClaimState);
  },
  activeClaimPreferenceRevision: __t.option(__t.u64()),
  activeClaimDigestRevision: __t.option(__t.u64()),
  activeClaimLeaseUntil: __t.option(__t.timestamp()),
  activeClaimNextAttemptAt: __t.option(__t.timestamp()),
});
export type NotificationDigestScheduleView = __Infer<typeof NotificationDigestScheduleView>;

// The tagged union or sum type for the algebraic type `NotificationDigestTerminalOutcome`.
export const NotificationDigestTerminalOutcome = __t.enum("NotificationDigestTerminalOutcome", {
  Succeeded: __t.unit(),
  Suppressed: __t.unit(),
  PermanentFailure: __t.unit(),
});
export type NotificationDigestTerminalOutcome = __Infer<typeof NotificationDigestTerminalOutcome>;

export const NotificationGroup = __t.object("NotificationGroup", {
  baseKey: __t.string(),
  groupKey: __t.string(),
  notificationId: __t.uuid(),
  groupRevision: __t.u64(),
  windowStartedAt: __t.timestamp(),
  windowExpiresAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationGroup = __Infer<typeof NotificationGroup>;

// The tagged union or sum type for the algebraic type `NotificationKind`.
export const NotificationKind = __t.enum("NotificationKind", {
  Mention: __t.unit(),
  Reply: __t.unit(),
  Assignment: __t.unit(),
  Decision: __t.unit(),
  Agent: __t.unit(),
  System: __t.unit(),
});
export type NotificationKind = __Infer<typeof NotificationKind>;

export const NotificationPreference = __t.object("NotificationPreference", {
  key: __t.string(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get directMode() {
    return NotificationDeliveryMode;
  },
  get importantMode() {
    return NotificationDeliveryMode;
  },
  get ambientMode() {
    return NotificationDeliveryMode;
  },
  muteStartLocalMinute: __t.option(__t.u16()),
  muteEndLocalMinute: __t.option(__t.u16()),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type NotificationPreference = __Infer<typeof NotificationPreference>;

// The tagged union or sum type for the algebraic type `NotificationTier`.
export const NotificationTier = __t.enum("NotificationTier", {
  Direct: __t.unit(),
  Important: __t.unit(),
  Ambient: __t.unit(),
});
export type NotificationTier = __Infer<typeof NotificationTier>;

export const OutboxJob = __t.object("OutboxJob", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  effectKey: __t.string(),
  get state() {
    return OutboxState;
  },
  kind: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.option(__t.u64()),
  intentId: __t.option(__t.uuid()),
  recipientId: __t.option(__t.identity()),
  channel: __t.string(),
  authorizationEpoch: __t.option(__t.u64()),
  minimalMessage: __t.string(),
  payloadResourceId: __t.option(__t.uuid()),
  rebuildId: __t.option(__t.uuid()),
  generation: __t.option(__t.u64()),
  fileId: __t.option(__t.uuid()),
  version: __t.option(__t.u64()),
  runId: __t.option(__t.uuid()),
  expiresAt: __t.timestamp(),
  attempt: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  nextAttemptAt: __t.timestamp(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type OutboxJob = __Infer<typeof OutboxJob>;

export const OutboxJobEnvelopeView = __t.object("OutboxJobEnvelopeView", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  kind: __t.string(),
  effectKey: __t.string(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.option(__t.u64()),
  intentId: __t.option(__t.uuid()),
  recipientId: __t.option(__t.identity()),
  channel: __t.string(),
  authorizationEpoch: __t.option(__t.u64()),
  minimalMessage: __t.string(),
  payloadResourceId: __t.option(__t.uuid()),
  rebuildId: __t.option(__t.uuid()),
  generation: __t.option(__t.u64()),
  fileId: __t.option(__t.uuid()),
  version: __t.option(__t.u64()),
  runId: __t.option(__t.uuid()),
  createdAt: __t.timestamp(),
  nextAttemptAt: __t.timestamp(),
  attempt: __t.u32(),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseUntil: __t.option(__t.timestamp()),
  leaseGeneration: __t.u64(),
  lastError: __t.string(),
});
export type OutboxJobEnvelopeView = __Infer<typeof OutboxJobEnvelopeView>;

// The tagged union or sum type for the algebraic type `OutboxState`.
export const OutboxState = __t.enum("OutboxState", {
  Pending: __t.unit(),
  Leased: __t.unit(),
  Succeeded: __t.unit(),
  Retry: __t.unit(),
  OutcomeUnknown: __t.unit(),
  DeadLetter: __t.unit(),
});
export type OutboxState = __Infer<typeof OutboxState>;

export const PendingOperatorTransfer = __t.object("PendingOperatorTransfer", {
  singleton: __t.u8(),
  proposedSubject: __t.string(),
  authorityRevision: __t.u64(),
  proposedBy: __t.identity(),
  proposedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PendingOperatorTransfer = __Infer<typeof PendingOperatorTransfer>;

export const PlaceWorkspaceLegalHoldInput = __t.object("PlaceWorkspaceLegalHoldInput", {
  workspaceId: __t.uuid(),
  reason: __t.string(),
  clientRequestId: __t.uuid(),
});
export type PlaceWorkspaceLegalHoldInput = __Infer<typeof PlaceWorkspaceLegalHoldInput>;

export const PlatformAuditLog = __t.object("PlatformAuditLog", {
  id: __t.uuid(),
  actorIdentity: __t.identity(),
  actorSubject: __t.string(),
  workspaceId: __t.option(__t.uuid()),
  action: __t.string(),
  resource: __t.string(),
  requestId: __t.uuid(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type PlatformAuditLog = __Infer<typeof PlatformAuditLog>;

export const PlatformAuthority = __t.object("PlatformAuthority", {
  singleton: __t.u8(),
  operatorSubject: __t.string(),
  revision: __t.u64(),
  updatedBy: __t.identity(),
  configuredAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PlatformAuthority = __Infer<typeof PlatformAuthority>;

export const PlatformCommandReceipt = __t.object("PlatformCommandReceipt", {
  key: __t.string(),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  inputHash: __t.string(),
  actorSubject: __t.string(),
  committedRevision: __t.u64(),
  committedAt: __t.timestamp(),
});
export type PlatformCommandReceipt = __Infer<typeof PlatformCommandReceipt>;

export const Poll = __t.object("Poll", {
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  allowsMultiple: __t.bool(),
  closed: __t.bool(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Poll = __Infer<typeof Poll>;

export const PollOption = __t.object("PollOption", {
  id: __t.uuid(),
  postId: __t.uuid(),
  label: __t.string(),
  position: __t.u32(),
});
export type PollOption = __Infer<typeof PollOption>;

export const PollVote = __t.object("PollVote", {
  key: __t.string(),
  postId: __t.uuid(),
  optionId: __t.uuid(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type PollVote = __Infer<typeof PollVote>;

export const Post = __t.object("Post", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  authorIdentity: __t.identity(),
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  get kind() {
    return PostKind;
  },
  get state() {
    return PostState;
  },
  locked: __t.bool(),
  title: __t.string(),
  body: __t.string(),
  revision: __t.u64(),
  activitySequence: __t.u64(),
  lastActivityAt: __t.timestamp(),
  deleted: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Post = __Infer<typeof Post>;

export const PostActivity = __t.object("PostActivity", {
  key: __t.string(),
  postId: __t.uuid(),
  sequence: __t.u64(),
  actorIdentity: __t.identity(),
  kind: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostActivity = __Infer<typeof PostActivity>;

// The tagged union or sum type for the algebraic type `PostKind`.
export const PostKind = __t.enum("PostKind", {
  Discussion: __t.unit(),
  Question: __t.unit(),
  Announcement: __t.unit(),
  Decision: __t.unit(),
  Task: __t.unit(),
  Poll: __t.unit(),
  Incident: __t.unit(),
  MediaDrop: __t.unit(),
});
export type PostKind = __Infer<typeof PostKind>;

export const PostMention = __t.object("PostMention", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  createdAt: __t.timestamp(),
});
export type PostMention = __Infer<typeof PostMention>;

export const PostPin = __t.object("PostPin", {
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  pinnedBy: __t.identity(),
  pinnedAt: __t.timestamp(),
});
export type PostPin = __Infer<typeof PostPin>;

export const PostReaction = __t.object("PostReaction", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostReaction = __Infer<typeof PostReaction>;

// The tagged union or sum type for the algebraic type `PostState`.
export const PostState = __t.enum("PostState", {
  Active: __t.unit(),
  Resolved: __t.unit(),
  Archived: __t.unit(),
});
export type PostState = __Infer<typeof PostState>;

export const PostTag = __t.object("PostTag", {
  key: __t.string(),
  postId: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  tag: __t.string(),
  createdAt: __t.timestamp(),
});
export type PostTag = __Infer<typeof PostTag>;

export const PostUserState = __t.object("PostUserState", {
  key: __t.string(),
  postId: __t.uuid(),
  identity: __t.identity(),
  following: __t.bool(),
  bookmarked: __t.bool(),
  lastReadSequence: __t.u64(),
  readAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type PostUserState = __Infer<typeof PostUserState>;

export const PrepareAgentToolCallInput = __t.object("PrepareAgentToolCallInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  providerCallId: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  normalizedArgsHash: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  effectKey: __t.string(),
  nonceHash: __t.string(),
});
export type PrepareAgentToolCallInput = __Infer<typeof PrepareAgentToolCallInput>;

// The tagged union or sum type for the algebraic type `PresenceDeviceKind`.
export const PresenceDeviceKind = __t.enum("PresenceDeviceKind", {
  Web: __t.unit(),
  Desktop: __t.unit(),
  Mobile: __t.unit(),
  Other: __t.unit(),
});
export type PresenceDeviceKind = __Infer<typeof PresenceDeviceKind>;

export const PresenceExpirySchedule = __t.object("PresenceExpirySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  presenceKey: __t.string(),
  expectedExpiresAt: __t.timestamp(),
});
export type PresenceExpirySchedule = __Infer<typeof PresenceExpirySchedule>;

export const PresenceSession = __t.object("PresenceSession", {
  key: __t.string(),
  scopeKey: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  sessionId: __t.uuid(),
  get deviceKind() {
    return PresenceDeviceKind;
  },
  deviceLabel: __t.string(),
  get status() {
    return PresenceStatus;
  },
  createdAt: __t.timestamp(),
  heartbeatAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type PresenceSession = __Infer<typeof PresenceSession>;

// The tagged union or sum type for the algebraic type `PresenceStatus`.
export const PresenceStatus = __t.enum("PresenceStatus", {
  Online: __t.unit(),
  Away: __t.unit(),
  DoNotDisturb: __t.unit(),
});
export type PresenceStatus = __Infer<typeof PresenceStatus>;

export const ProposeDmPromotionInput = __t.object("ProposeDmPromotionInput", {
  conversationId: __t.uuid(),
  destinationSpaceId: __t.uuid(),
  title: __t.string(),
  body: __t.string(),
  sourceMessageIds: __t.array(__t.uuid()),
  expiresInSeconds: __t.u32(),
  clientRequestId: __t.uuid(),
});
export type ProposeDmPromotionInput = __Infer<typeof ProposeDmPromotionInput>;

export const RecordAgentProviderDispatchInput = __t.object("RecordAgentProviderDispatchInput", {
  runId: __t.uuid(),
  providerSequence: __t.u64(),
  leaseGeneration: __t.u64(),
  authorizationEpoch: __t.u64(),
  requestId: __t.string(),
  inputFingerprint: __t.string(),
  canonicalInput: __t.string(),
  inputBytes: __t.u64(),
  contextBindingHash: __t.string(),
  contextJson: __t.string(),
});
export type RecordAgentProviderDispatchInput = __Infer<typeof RecordAgentProviderDispatchInput>;

export const RecordFileOrphanInput = __t.object("RecordFileOrphanInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  key: __t.string(),
});
export type RecordFileOrphanInput = __Infer<typeof RecordFileOrphanInput>;

export const RecordNotificationDigestOutcomeInput = __t.object("RecordNotificationDigestOutcomeInput", {
  claimId: __t.uuid(),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
  get outcome() {
    return NotificationDigestCompletionOutcome;
  },
  reconciled: __t.bool(),
  providerReference: __t.string(),
  code: __t.string(),
  retryAfterSeconds: __t.u32(),
});
export type RecordNotificationDigestOutcomeInput = __Infer<typeof RecordNotificationDigestOutcomeInput>;

export const RegisterCleanFileObjectInput = __t.object("RegisterCleanFileObjectInput", {
  jobId: __t.uuid(),
  leaseGeneration: __t.u64(),
  fileId: __t.uuid(),
  expectedRevision: __t.u64(),
  cleanKey: __t.string(),
  objectVersion: __t.string(),
  checksumSha256: __t.string(),
});
export type RegisterCleanFileObjectInput = __Infer<typeof RegisterCleanFileObjectInput>;

export const ReleaseFileDeletionInput = __t.object("ReleaseFileDeletionInput", {
  get claim() {
    return FileDeletionClaimInput;
  },
  code: __t.string(),
});
export type ReleaseFileDeletionInput = __Infer<typeof ReleaseFileDeletionInput>;

export const ReleaseWorkspaceLegalHoldInput = __t.object("ReleaseWorkspaceLegalHoldInput", {
  holdId: __t.uuid(),
  expectedRevision: __t.u64(),
  releaseReason: __t.string(),
  clientRequestId: __t.uuid(),
});
export type ReleaseWorkspaceLegalHoldInput = __Infer<typeof ReleaseWorkspaceLegalHoldInput>;

export const ReplyAncestry = __t.object("ReplyAncestry", {
  key: __t.string(),
  ancestorId: __t.uuid(),
  descendantId: __t.uuid(),
  threadId: __t.uuid(),
  depth: __t.u32(),
});
export type ReplyAncestry = __Infer<typeof ReplyAncestry>;

export const RequestWorkspaceExportInput = __t.object("RequestWorkspaceExportInput", {
  workspaceId: __t.uuid(),
  clientRequestId: __t.uuid(),
});
export type RequestWorkspaceExportInput = __Infer<typeof RequestWorkspaceExportInput>;

export const SaveAgentCheckpointInput = __t.object("SaveAgentCheckpointInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  sequence: __t.u64(),
  get state() {
    return AgentRunState;
  },
  code: __t.string(),
  detailsJson: __t.string(),
  createdAtMillis: __t.u64(),
});
export type SaveAgentCheckpointInput = __Infer<typeof SaveAgentCheckpointInput>;

export const SaveAgentProgressInput = __t.object("SaveAgentProgressInput", {
  runId: __t.uuid(),
  leaseGeneration: __t.u64(),
  sequence: __t.u64(),
  outputTokens: __t.u64(),
  costMicros: __t.u64(),
  toolCalls: __t.u32(),
  toolResultsJson: __t.string(),
  providerInputBytes: __t.u64(),
  pendingStepJson: __t.string(),
});
export type SaveAgentProgressInput = __Infer<typeof SaveAgentProgressInput>;

export const SearchDocumentSnapshot = __t.object("SearchDocumentSnapshot", {
  effectKey: __t.string(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  tombstone: __t.bool(),
  allowedIdentities: __t.array(__t.identity()),
  createdAt: __t.timestamp(),
});
export type SearchDocumentSnapshot = __Infer<typeof SearchDocumentSnapshot>;

export const SearchWorkItem = __t.object("SearchWorkItem", {
  jobId: __t.uuid(),
  effectKey: __t.string(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  resourceType: __t.string(),
  resourceId: __t.uuid(),
  resourceRevision: __t.u64(),
  aclRevision: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  tombstone: __t.bool(),
  allowedIdentities: __t.array(__t.identity()),
  get state() {
    return OutboxState;
  },
  leaseGeneration: __t.u64(),
});
export type SearchWorkItem = __Infer<typeof SearchWorkItem>;

export const ServiceGrant = __t.object("ServiceGrant", {
  key: __t.string(),
  serviceIdentity: __t.identity(),
  workspaceId: __t.uuid(),
  kind: __t.string(),
  enabled: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ServiceGrant = __Infer<typeof ServiceGrant>;

export const ServicePrincipal = __t.object("ServicePrincipal", {
  identity: __t.identity(),
  name: __t.string(),
  enabled: __t.bool(),
  canRunAgents: __t.bool(),
  canProcessOutbox: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ServicePrincipal = __Infer<typeof ServicePrincipal>;

export const SetAgentToolPolicyInput = __t.object("SetAgentToolPolicyInput", {
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  expectedInstallationEpoch: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type SetAgentToolPolicyInput = __Infer<typeof SetAgentToolPolicyInput>;

export const SetNotificationPreferenceInput = __t.object("SetNotificationPreferenceInput", {
  workspaceId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get directMode() {
    return NotificationDeliveryMode;
  },
  get importantMode() {
    return NotificationDeliveryMode;
  },
  get ambientMode() {
    return NotificationDeliveryMode;
  },
  muteStartLocalMinute: __t.option(__t.u16()),
  muteEndLocalMinute: __t.option(__t.u16()),
  timeZone: __t.string(),
  digestLocalMinute: __t.u16(),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type SetNotificationPreferenceInput = __Infer<typeof SetNotificationPreferenceInput>;

export const Space = __t.object("Space", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  get visibility() {
    return SpaceVisibility;
  },
  archived: __t.bool(),
  revision: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Space = __Infer<typeof Space>;

export const SpaceMember = __t.object("SpaceMember", {
  key: __t.string(),
  spaceId: __t.uuid(),
  identity: __t.identity(),
  active: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SpaceMember = __Infer<typeof SpaceMember>;

// The tagged union or sum type for the algebraic type `SpaceVisibility`.
export const SpaceVisibility = __t.enum("SpaceVisibility", {
  Workspace: __t.unit(),
  Private: __t.unit(),
});
export type SpaceVisibility = __Infer<typeof SpaceVisibility>;

export const TaskItem = __t.object("TaskItem", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  assigneeIdentity: __t.identity(),
  title: __t.string(),
  get status() {
    return TaskStatus;
  },
  createdBy: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type TaskItem = __Infer<typeof TaskItem>;

// The tagged union or sum type for the algebraic type `TaskStatus`.
export const TaskStatus = __t.enum("TaskStatus", {
  Todo: __t.unit(),
  InProgress: __t.unit(),
  Done: __t.unit(),
  Canceled: __t.unit(),
});
export type TaskStatus = __Infer<typeof TaskStatus>;

// The tagged union or sum type for the algebraic type `ToolCallState`.
export const ToolCallState = __t.enum("ToolCallState", {
  Proposed: __t.unit(),
  AwaitingApproval: __t.unit(),
  Approved: __t.unit(),
  Executing: __t.unit(),
  Succeeded: __t.unit(),
  Failed: __t.unit(),
  OutcomeUnknown: __t.unit(),
  Canceled: __t.unit(),
});
export type ToolCallState = __Infer<typeof ToolCallState>;

// The tagged union or sum type for the algebraic type `ToolEffectClass`.
export const ToolEffectClass = __t.enum("ToolEffectClass", {
  Read: __t.unit(),
  External: __t.unit(),
  Destructive: __t.unit(),
});
export type ToolEffectClass = __Infer<typeof ToolEffectClass>;

export const TrustedOidcAudience = __t.object("TrustedOidcAudience", {
  audience: __t.string(),
  configuredAt: __t.timestamp(),
});
export type TrustedOidcAudience = __Infer<typeof TrustedOidcAudience>;

export const TrustedTool = __t.object("TrustedTool", {
  key: __t.string(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredAt: __t.timestamp(),
});
export type TrustedTool = __Infer<typeof TrustedTool>;

export const UpdatePostLifecycleInput = __t.object("UpdatePostLifecycleInput", {
  postId: __t.uuid(),
  get state() {
    return PostState;
  },
  locked: __t.bool(),
  ownerIdentity: __t.identity(),
  assigneeIdentity: __t.option(__t.identity()),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type UpdatePostLifecycleInput = __Infer<typeof UpdatePostLifecycleInput>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.string(),
  disabled: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const VisibleAgentInstallation = __t.object("VisibleAgentInstallation", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  enabled: __t.bool(),
  maxRunTokens: __t.u64(),
  maxRunCostMicros: __t.u64(),
  installedBy: __t.identity(),
});
export type VisibleAgentInstallation = __Infer<typeof VisibleAgentInstallation>;

export const VisibleAgentRun = __t.object("VisibleAgentRun", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  installationId: __t.uuid(),
  spaceId: __t.uuid(),
  threadId: __t.option(__t.uuid()),
  initiatedBy: __t.identity(),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  cancelRequested: __t.bool(),
  promptSummary: __t.string(),
  outputSummary: __t.string(),
  usedTokens: __t.u64(),
  usedCostMicros: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentRun = __Infer<typeof VisibleAgentRun>;

export const VisibleAgentScope = __t.object("VisibleAgentScope", {
  installationId: __t.uuid(),
  spaceId: __t.option(__t.uuid()),
  get capability() {
    return AgentCapability;
  },
  enabled: __t.bool(),
});
export type VisibleAgentScope = __Infer<typeof VisibleAgentScope>;

export const VisibleAgentToolCall = __t.object("VisibleAgentToolCall", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get effectClass() {
    return ToolEffectClass;
  },
  requiresApproval: __t.bool(),
  get state() {
    return ToolCallState;
  },
  resultSummary: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentToolCall = __Infer<typeof VisibleAgentToolCall>;

export const VisibleAgentToolPolicy = __t.object("VisibleAgentToolPolicy", {
  installationId: __t.uuid(),
  toolName: __t.string(),
  toolVersion: __t.string(),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass;
  },
  trustedToolRevision: __t.u64(),
  requiresApproval: __t.bool(),
  approvalTtlSeconds: __t.u32(),
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type VisibleAgentToolPolicy = __Infer<typeof VisibleAgentToolPolicy>;

export const VisibleApproval = __t.object("VisibleApproval", {
  id: __t.uuid(),
  runId: __t.uuid(),
  toolCallId: __t.uuid(),
  get effectClass() {
    return ToolEffectClass;
  },
  get state() {
    return ApprovalState;
  },
  decidedBy: __t.option(__t.identity()),
  expiresAt: __t.timestamp(),
});
export type VisibleApproval = __Infer<typeof VisibleApproval>;

export const VisibleCommandReceipt = __t.object("VisibleCommandReceipt", {
  workspaceId: __t.option(__t.uuid()),
  operation: __t.string(),
  clientRequestId: __t.uuid(),
  resultType: __t.string(),
  resultId: __t.uuid(),
  committedAt: __t.timestamp(),
});
export type VisibleCommandReceipt = __Infer<typeof VisibleCommandReceipt>;

export const VisibleFile = __t.object("VisibleFile", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  spaceId: __t.uuid(),
  ownerIdentity: __t.identity(),
  fileName: __t.string(),
  declaredSizeBytes: __t.u64(),
  detectedType: __t.string(),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleFile = __Infer<typeof VisibleFile>;

export const VisiblePollOption = __t.object("VisiblePollOption", {
  id: __t.uuid(),
  postId: __t.uuid(),
  label: __t.string(),
  position: __t.u32(),
  voteCount: __t.u64(),
  viewerSelected: __t.bool(),
});
export type VisiblePollOption = __Infer<typeof VisiblePollOption>;

export const VisiblePostUserState = __t.object("VisiblePostUserState", {
  postId: __t.uuid(),
  following: __t.bool(),
  bookmarked: __t.bool(),
  unread: __t.bool(),
  lastReadSequence: __t.u64(),
  readAt: __t.option(__t.timestamp()),
});
export type VisiblePostUserState = __Infer<typeof VisiblePostUserState>;

export const VisiblePresence = __t.object("VisiblePresence", {
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get status() {
    return PresenceStatus;
  },
  expiresAt: __t.timestamp(),
});
export type VisiblePresence = __Infer<typeof VisiblePresence>;

export const VisibleUser = __t.object("VisibleUser", {
  identity: __t.identity(),
  displayName: __t.string(),
});
export type VisibleUser = __Infer<typeof VisibleUser>;

export const VisibleWorkspaceExport = __t.object("VisibleWorkspaceExport", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceExportState;
  },
  artifactKey: __t.string(),
  contentHash: __t.string(),
  sizeBytes: __t.u64(),
  expiresAt: __t.option(__t.timestamp()),
  failureReason: __t.string(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type VisibleWorkspaceExport = __Infer<typeof VisibleWorkspaceExport>;

export const VisibleWorkspaceLegalHold = __t.object("VisibleWorkspaceLegalHold", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLegalHoldState;
  },
  placedAt: __t.timestamp(),
  releasedAt: __t.option(__t.timestamp()),
  revision: __t.u64(),
});
export type VisibleWorkspaceLegalHold = __Infer<typeof VisibleWorkspaceLegalHold>;

export const VisibleWorkspaceLifecycle = __t.object("VisibleWorkspaceLifecycle", {
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLifecycleState;
  },
  lifecycleEpoch: __t.u64(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  deletionExecuteAfter: __t.option(__t.timestamp()),
  revision: __t.u64(),
});
export type VisibleWorkspaceLifecycle = __Infer<typeof VisibleWorkspaceLifecycle>;

export const VisibleWorkspaceMember = __t.object("VisibleWorkspaceMember", {
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get role() {
    return WorkspaceRole;
  },
  active: __t.bool(),
});
export type VisibleWorkspaceMember = __Infer<typeof VisibleWorkspaceMember>;

export const WorkerEffectAcquireInput = __t.object("WorkerEffectAcquireInput", {
  effectKey: __t.string(),
  identityFingerprint: __t.string(),
  payloadFingerprint: __t.string(),
  ownerId: __t.string(),
  ownerGeneration: __t.u64(),
  workspaceId: __t.uuid(),
  runId: __t.option(__t.uuid()),
  authorityJobId: __t.option(__t.uuid()),
  leaseExpiresAtMillis: __t.u64(),
  allowTakeover: __t.bool(),
});
export type WorkerEffectAcquireInput = __Infer<typeof WorkerEffectAcquireInput>;

export const WorkerEffectLedger = __t.object("WorkerEffectLedger", {
  effectKey: __t.string(),
  identityFingerprint: __t.string(),
  payloadFingerprint: __t.string(),
  workspaceId: __t.uuid(),
  authorityKind: __t.string(),
  get state() {
    return WorkerEffectState;
  },
  ownerIdentity: __t.identity(),
  ownerId: __t.string(),
  ownerGeneration: __t.u64(),
  leaseExpiresAtMillis: __t.u64(),
  providerReference: __t.string(),
  resultJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type WorkerEffectLedger = __Infer<typeof WorkerEffectLedger>;

// The tagged union or sum type for the algebraic type `WorkerEffectState`.
export const WorkerEffectState = __t.enum("WorkerEffectState", {
  Started: __t.unit(),
  Succeeded: __t.unit(),
  OutcomeUnknown: __t.unit(),
  FailedPermanent: __t.unit(),
});
export type WorkerEffectState = __Infer<typeof WorkerEffectState>;

export const WorkerEffectUpdateInput = __t.object("WorkerEffectUpdateInput", {
  effectKey: __t.string(),
  identityFingerprint: __t.string(),
  ownerId: __t.string(),
  ownerGeneration: __t.u64(),
  leaseExpiresAtMillis: __t.u64(),
  get outcome() {
    return WorkerEffectState;
  },
  providerReference: __t.string(),
  resultJson: __t.string(),
});
export type WorkerEffectUpdateInput = __Infer<typeof WorkerEffectUpdateInput>;

export const Workspace = __t.object("Workspace", {
  id: __t.uuid(),
  name: __t.string(),
  ownerIdentity: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Workspace = __Infer<typeof Workspace>;

export const WorkspaceExport = __t.object("WorkspaceExport", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  requestedBy: __t.identity(),
  get state() {
    return WorkspaceExportState;
  },
  lifecycleEpoch: __t.u64(),
  workspaceRevision: __t.u64(),
  artifactKey: __t.string(),
  contentHash: __t.string(),
  artifactVersion: __t.string(),
  sizeBytes: __t.u64(),
  expiresAt: __t.option(__t.timestamp()),
  failureReason: __t.string(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceExport = __Infer<typeof WorkspaceExport>;

// The tagged union or sum type for the algebraic type `WorkspaceExportCleanupOutcome`.
export const WorkspaceExportCleanupOutcome = __t.enum("WorkspaceExportCleanupOutcome", {
  Deleted: __t.unit(),
  NotFound: __t.unit(),
  Retry: __t.unit(),
  OutcomeUnknown: __t.unit(),
  Failed: __t.unit(),
});
export type WorkspaceExportCleanupOutcome = __Infer<typeof WorkspaceExportCleanupOutcome>;

export const WorkspaceExportCleanupPlanView = __t.object("WorkspaceExportCleanupPlanView", {
  jobId: __t.uuid(),
  exportId: __t.uuid(),
  workspaceId: __t.uuid(),
  exportRevision: __t.u64(),
  artifactKey: __t.string(),
  contentHash: __t.string(),
  artifactVersion: __t.string(),
  sizeBytes: __t.u64(),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
});
export type WorkspaceExportCleanupPlanView = __Infer<typeof WorkspaceExportCleanupPlanView>;

// The tagged union or sum type for the algebraic type `WorkspaceExportCompletionOutcome`.
export const WorkspaceExportCompletionOutcome = __t.enum("WorkspaceExportCompletionOutcome", {
  Ready: __t.unit(),
  Retry: __t.unit(),
  OutcomeUnknown: __t.unit(),
  Failed: __t.unit(),
});
export type WorkspaceExportCompletionOutcome = __Infer<typeof WorkspaceExportCompletionOutcome>;

export const WorkspaceExportExpirySchedule = __t.object("WorkspaceExportExpirySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  exportId: __t.uuid(),
  expectedRevision: __t.u64(),
});
export type WorkspaceExportExpirySchedule = __Infer<typeof WorkspaceExportExpirySchedule>;

export const WorkspaceExportPlanView = __t.object("WorkspaceExportPlanView", {
  jobId: __t.uuid(),
  exportId: __t.uuid(),
  workspaceId: __t.uuid(),
  lifecycleEpoch: __t.u64(),
  workspaceRevision: __t.u64(),
  exportRevision: __t.u64(),
  reconcileOnly: __t.bool(),
  get state() {
    return OutboxState;
  },
  leaseOwner: __t.option(__t.identity()),
  workerSlotId: __t.string(),
  leaseGeneration: __t.u64(),
});
export type WorkspaceExportPlanView = __Infer<typeof WorkspaceExportPlanView>;

// The tagged union or sum type for the algebraic type `WorkspaceExportState`.
export const WorkspaceExportState = __t.enum("WorkspaceExportState", {
  Requested: __t.unit(),
  Ready: __t.unit(),
  Failed: __t.unit(),
  Expired: __t.unit(),
  Cleaned: __t.unit(),
});
export type WorkspaceExportState = __Infer<typeof WorkspaceExportState>;

export const WorkspaceLegalHold = __t.object("WorkspaceLegalHold", {
  id: __t.uuid(),
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLegalHoldState;
  },
  reason: __t.string(),
  placedByIdentity: __t.identity(),
  placedBySubject: __t.string(),
  placedAt: __t.timestamp(),
  releasedByIdentity: __t.option(__t.identity()),
  releasedBySubject: __t.string(),
  releaseReason: __t.string(),
  releasedAt: __t.option(__t.timestamp()),
  revision: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceLegalHold = __Infer<typeof WorkspaceLegalHold>;

// The tagged union or sum type for the algebraic type `WorkspaceLegalHoldState`.
export const WorkspaceLegalHoldState = __t.enum("WorkspaceLegalHoldState", {
  Active: __t.unit(),
  Released: __t.unit(),
});
export type WorkspaceLegalHoldState = __Infer<typeof WorkspaceLegalHoldState>;

export const WorkspaceLifecycle = __t.object("WorkspaceLifecycle", {
  workspaceId: __t.uuid(),
  get state() {
    return WorkspaceLifecycleState;
  },
  lifecycleEpoch: __t.u64(),
  deletedContentRetentionDays: __t.option(__t.u32()),
  deletionGraceDays: __t.option(__t.u16()),
  deletionRequestedBy: __t.option(__t.identity()),
  deletionRequestedAt: __t.option(__t.timestamp()),
  deletionExecuteAfter: __t.option(__t.timestamp()),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceLifecycle = __Infer<typeof WorkspaceLifecycle>;

export const WorkspaceLifecycleCommandInput = __t.object("WorkspaceLifecycleCommandInput", {
  workspaceId: __t.uuid(),
  expectedRevision: __t.u64(),
  clientRequestId: __t.uuid(),
});
export type WorkspaceLifecycleCommandInput = __Infer<typeof WorkspaceLifecycleCommandInput>;

export const WorkspaceLifecycleDrainSchedule = __t.object("WorkspaceLifecycleDrainSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  workspaceId: __t.uuid(),
  lifecycleEpoch: __t.u64(),
});
export type WorkspaceLifecycleDrainSchedule = __Infer<typeof WorkspaceLifecycleDrainSchedule>;

// The tagged union or sum type for the algebraic type `WorkspaceLifecycleState`.
export const WorkspaceLifecycleState = __t.enum("WorkspaceLifecycleState", {
  Active: __t.unit(),
  DeletionRequested: __t.unit(),
  DeletionFenced: __t.unit(),
});
export type WorkspaceLifecycleState = __Infer<typeof WorkspaceLifecycleState>;

export const WorkspaceMember = __t.object("WorkspaceMember", {
  key: __t.string(),
  workspaceId: __t.uuid(),
  identity: __t.identity(),
  get role() {
    return WorkspaceRole;
  },
  active: __t.bool(),
  authzEpoch: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceMember = __Infer<typeof WorkspaceMember>;

// The tagged union or sum type for the algebraic type `WorkspaceRole`.
export const WorkspaceRole = __t.enum("WorkspaceRole", {
  Owner: __t.unit(),
  Admin: __t.unit(),
  Member: __t.unit(),
  Guest: __t.unit(),
});
export type WorkspaceRole = __Infer<typeof WorkspaceRole>;
