// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ContributionKind,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  threadId: __t.uuid().name("thread_id"),
  authorIdentity: __t.identity().name("author_identity"),
  agentInstallationId: __t.option(__t.uuid()).name("agent_installation_id"),
  agentRunId: __t.option(__t.uuid()).name("agent_run_id"),
  parentContributionId: __t.option(__t.uuid()).name("parent_contribution_id"),
  get kind() {
    return ContributionKind;
  },
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
