// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentRunState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  installationId: __t.uuid().name("installation_id"),
  spaceId: __t.uuid().name("space_id"),
  threadId: __t.option(__t.uuid()).name("thread_id"),
  initiatedBy: __t.identity().name("initiated_by"),
  get state() {
    return AgentRunState;
  },
  version: __t.u64(),
  cancelRequested: __t.bool().name("cancel_requested"),
  promptSummary: __t.string().name("prompt_summary"),
  outputSummary: __t.string().name("output_summary"),
  usedTokens: __t.u64().name("used_tokens"),
  usedCostMicros: __t.u64().name("used_cost_micros"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
