// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  sequenceKey: __t.string().name("sequence_key"),
  conversationId: __t.uuid().name("conversation_id"),
  authorIdentity: __t.identity().name("author_identity"),
  workspaceId: __t.uuid().name("workspace_id"),
  sequence: __t.u64(),
  parentMessageId: __t.option(__t.uuid()).name("parent_message_id"),
  body: __t.string(),
  revision: __t.u64(),
  deleted: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  editedAt: __t.option(__t.timestamp()).name("edited_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
