// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentCapability,
  ToolEffectClass,
} from "./types";


export default __t.row({
  installationId: __t.uuid().name("installation_id"),
  toolName: __t.string().name("tool_name"),
  toolVersion: __t.string().name("tool_version"),
  get capability() {
    return AgentCapability;
  },
  get effectClass() {
    return ToolEffectClass.name("effect_class");
  },
  trustedToolRevision: __t.u64().name("trusted_tool_revision"),
  requiresApproval: __t.bool().name("requires_approval"),
  approvalTtlSeconds: __t.u32().name("approval_ttl_seconds"),
  enabled: __t.bool(),
  revision: __t.u64(),
  configuredBy: __t.identity().name("configured_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
