// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  conversationId: __t.uuid().name("conversation_id"),
  identity: __t.identity(),
  workspaceId: __t.uuid().name("workspace_id"),
  joinedAt: __t.timestamp().name("joined_at"),
  leftAt: __t.option(__t.timestamp()).name("left_at"),
  participantEpoch: __t.u64().name("participant_epoch"),
});
