// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  runId: __t.uuid().name("run_id"),
  runResourceKey: __t.string().name("run_resource_key"),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  resourceRevision: __t.u64().name("resource_revision"),
  sourceHash: __t.string().name("source_hash"),
  trustClass: __t.string().name("trust_class"),
  redactionSummary: __t.string().name("redaction_summary"),
  policyVersion: __t.u32().name("policy_version"),
  createdAt: __t.timestamp().name("created_at"),
});
