// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ToolEffectClass,
  ToolCallState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  runId: __t.uuid().name("run_id"),
  toolName: __t.string().name("tool_name"),
  toolVersion: __t.string().name("tool_version"),
  get effectClass() {
    return ToolEffectClass.name("effect_class");
  },
  requiresApproval: __t.bool().name("requires_approval"),
  get state() {
    return ToolCallState;
  },
  resultSummary: __t.string().name("result_summary"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
