// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgentCapability,
} from "./types";


export default __t.row({
  installationId: __t.uuid().name("installation_id"),
  spaceId: __t.option(__t.uuid()).name("space_id"),
  get capability() {
    return AgentCapability;
  },
  enabled: __t.bool(),
});
