// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  name: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  enabled: __t.bool(),
  maxRunTokens: __t.u64().name("max_run_tokens"),
  maxRunCostMicros: __t.u64().name("max_run_cost_micros"),
  installedBy: __t.identity().name("installed_by"),
});
