// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ToolEffectClass,
  ApprovalState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  runId: __t.uuid().name("run_id"),
  toolCallId: __t.uuid().name("tool_call_id"),
  get effectClass() {
    return ToolEffectClass.name("effect_class");
  },
  get state() {
    return ApprovalState;
  },
  decidedBy: __t.option(__t.identity()).name("decided_by"),
  expiresAt: __t.timestamp().name("expires_at"),
});
