// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  actorIdentity: __t.identity().name("actor_identity"),
  effectivePrincipal: __t.string().name("effective_principal"),
  action: __t.string(),
  resourceType: __t.string().name("resource_type"),
  resourceId: __t.uuid().name("resource_id"),
  requestId: __t.uuid().name("request_id"),
  policyVersion: __t.u32().name("policy_version"),
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
