// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PresenceStatus,
} from "./types";


export default __t.row({
  workspaceId: __t.uuid().name("workspace_id"),
  identity: __t.identity(),
  get status() {
    return PresenceStatus;
  },
  expiresAt: __t.timestamp().name("expires_at"),
});
