// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  postId: __t.uuid().name("post_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  pinnedBy: __t.identity().name("pinned_by"),
  pinnedAt: __t.timestamp().name("pinned_at"),
});
