// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DmPromotionState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  conversationId: __t.uuid().name("conversation_id"),
  workspaceId: __t.uuid().name("workspace_id"),
  destinationSpaceId: __t.uuid().name("destination_space_id"),
  proposerIdentity: __t.identity().name("proposer_identity"),
  title: __t.string(),
  body: __t.string(),
  draftHash: __t.string().name("draft_hash"),
  sourceRevisionHash: __t.string().name("source_revision_hash"),
  proposalHash: __t.string().name("proposal_hash"),
  participantEpochHash: __t.string().name("participant_epoch_hash"),
  get state() {
    return DmPromotionState;
  },
  revision: __t.u64(),
  expiresAt: __t.timestamp().name("expires_at"),
  finalizedPostId: __t.option(__t.uuid()).name("finalized_post_id"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
