// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DmPromotionDecision,
} from "./types";


export default __t.row({
  key: __t.string(),
  proposalId: __t.uuid().name("proposal_id"),
  identity: __t.identity(),
  get decision() {
    return DmPromotionDecision;
  },
  proposalHash: __t.string().name("proposal_hash"),
  decidedAt: __t.timestamp().name("decided_at"),
});
