// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string(),
  ancestorMessageId: __t.uuid().name("ancestor_message_id"),
  descendantMessageId: __t.uuid().name("descendant_message_id"),
  conversationId: __t.uuid().name("conversation_id"),
  depth: __t.u32(),
});
