// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FileSecurityState,
} from "./types";


export default __t.row({
  id: __t.uuid(),
  workspaceId: __t.uuid().name("workspace_id"),
  spaceId: __t.uuid().name("space_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  fileName: __t.string().name("file_name"),
  declaredSizeBytes: __t.u64().name("declared_size_bytes"),
  detectedType: __t.string().name("detected_type"),
  get state() {
    return FileSecurityState;
  },
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
